//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 07:59:51 PM EST 
//


package org.openecomp.aai.inventory.v8;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}reserved-prop-names" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}edge-prop-names" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reservedPropNames",
    "edgePropNames"
})
@XmlRootElement(name = "aai-internal")
public class AaiInternal
    implements AAIDatum
{

    @XmlElement(name = "reserved-prop-names")
    protected List<ReservedPropNames> reservedPropNames;
    @XmlElement(name = "edge-prop-names")
    protected List<EdgePropNames> edgePropNames;

    /**
     * Gets the value of the reservedPropNames property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reservedPropNames property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReservedPropNames().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReservedPropNames }
     * 
     * 
     */
    public List<ReservedPropNames> getReservedPropNames() {
        if (reservedPropNames == null) {
            reservedPropNames = new ArrayList<ReservedPropNames>();
        }
        return this.reservedPropNames;
    }

    /**
     * Gets the value of the edgePropNames property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the edgePropNames property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEdgePropNames().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EdgePropNames }
     * 
     * 
     */
    public List<EdgePropNames> getEdgePropNames() {
        if (edgePropNames == null) {
            edgePropNames = new ArrayList<EdgePropNames>();
        }
        return this.edgePropNames;
    }

}
