//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 08:44:52 AM EST 
//


package org.openecomp.aai.inventory.v8;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="availability-zone-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="hypervisor-type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="operational-state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resource-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}relationship-list" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "availabilityZoneName",
    "hypervisorType",
    "operationalState",
    "resourceVersion",
    "relationshipList"
})
@XmlRootElement(name = "availability-zone")
public class AvailabilityZone
    implements AAIDatum
{

    @XmlElement(name = "availability-zone-name", required = true)
    protected String availabilityZoneName;
    @XmlElement(name = "hypervisor-type", required = true)
    protected String hypervisorType;
    @XmlElement(name = "operational-state")
    protected String operationalState;
    @XmlElement(name = "resource-version")
    protected String resourceVersion;
    @XmlElement(name = "relationship-list")
    protected RelationshipList relationshipList;

    /**
     * Gets the value of the availabilityZoneName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailabilityZoneName() {
        return availabilityZoneName;
    }

    /**
     * Sets the value of the availabilityZoneName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailabilityZoneName(String value) {
        this.availabilityZoneName = value;
    }

    /**
     * Gets the value of the hypervisorType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHypervisorType() {
        return hypervisorType;
    }

    /**
     * Sets the value of the hypervisorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHypervisorType(String value) {
        this.hypervisorType = value;
    }

    /**
     * Gets the value of the operationalState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationalState() {
        return operationalState;
    }

    /**
     * Sets the value of the operationalState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationalState(String value) {
        this.operationalState = value;
    }

    /**
     * Gets the value of the resourceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceVersion() {
        return resourceVersion;
    }

    /**
     * Sets the value of the resourceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceVersion(String value) {
        this.resourceVersion = value;
    }

    /**
     * Gets the value of the relationshipList property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipList }
     *     
     */
    public RelationshipList getRelationshipList() {
        return relationshipList;
    }

    /**
     * Sets the value of the relationshipList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipList }
     *     
     */
    public void setRelationshipList(RelationshipList value) {
        this.relationshipList = value;
    }

}
