//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.14 at 01:05:25 PM EST 
//


package org.openecomp.aai.inventory.v8;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cloud-owner" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cloud-region-id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cloud-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="owner-defined-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cloud-region-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="identity-url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cloud-zone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="complex-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resource-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}volume-groups" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}tenants" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}flavors" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}group-assignments" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}snapshots" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}images" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}availability-zones" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}relationship-list" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cloudOwner",
    "cloudRegionId",
    "cloudType",
    "ownerDefinedType",
    "cloudRegionVersion",
    "identityUrl",
    "cloudZone",
    "complexName",
    "resourceVersion",
    "volumeGroups",
    "tenants",
    "flavors",
    "groupAssignments",
    "snapshots",
    "images",
    "availabilityZones",
    "relationshipList"
})
@XmlRootElement(name = "cloud-region")
public class CloudRegion
    implements AAIDatum
{

    @XmlElement(name = "cloud-owner", required = true)
    protected String cloudOwner;
    @XmlElement(name = "cloud-region-id", required = true)
    protected String cloudRegionId;
    @XmlElement(name = "cloud-type")
    protected String cloudType;
    @XmlElement(name = "owner-defined-type")
    protected String ownerDefinedType;
    @XmlElement(name = "cloud-region-version")
    protected String cloudRegionVersion;
    @XmlElement(name = "identity-url")
    protected String identityUrl;
    @XmlElement(name = "cloud-zone")
    protected String cloudZone;
    @XmlElement(name = "complex-name")
    protected String complexName;
    @XmlElement(name = "resource-version")
    protected String resourceVersion;
    @XmlElement(name = "volume-groups")
    protected VolumeGroups volumeGroups;
    protected Tenants tenants;
    protected Flavors flavors;
    @XmlElement(name = "group-assignments")
    protected GroupAssignments groupAssignments;
    protected Snapshots snapshots;
    protected Images images;
    @XmlElement(name = "availability-zones")
    protected AvailabilityZones availabilityZones;
    @XmlElement(name = "relationship-list")
    protected RelationshipList relationshipList;

    /**
     * Gets the value of the cloudOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloudOwner() {
        return cloudOwner;
    }

    /**
     * Sets the value of the cloudOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloudOwner(String value) {
        this.cloudOwner = value;
    }

    /**
     * Gets the value of the cloudRegionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloudRegionId() {
        return cloudRegionId;
    }

    /**
     * Sets the value of the cloudRegionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloudRegionId(String value) {
        this.cloudRegionId = value;
    }

    /**
     * Gets the value of the cloudType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloudType() {
        return cloudType;
    }

    /**
     * Sets the value of the cloudType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloudType(String value) {
        this.cloudType = value;
    }

    /**
     * Gets the value of the ownerDefinedType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerDefinedType() {
        return ownerDefinedType;
    }

    /**
     * Sets the value of the ownerDefinedType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerDefinedType(String value) {
        this.ownerDefinedType = value;
    }

    /**
     * Gets the value of the cloudRegionVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloudRegionVersion() {
        return cloudRegionVersion;
    }

    /**
     * Sets the value of the cloudRegionVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloudRegionVersion(String value) {
        this.cloudRegionVersion = value;
    }

    /**
     * Gets the value of the identityUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentityUrl() {
        return identityUrl;
    }

    /**
     * Sets the value of the identityUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentityUrl(String value) {
        this.identityUrl = value;
    }

    /**
     * Gets the value of the cloudZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloudZone() {
        return cloudZone;
    }

    /**
     * Sets the value of the cloudZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloudZone(String value) {
        this.cloudZone = value;
    }

    /**
     * Gets the value of the complexName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComplexName() {
        return complexName;
    }

    /**
     * Sets the value of the complexName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComplexName(String value) {
        this.complexName = value;
    }

    /**
     * Gets the value of the resourceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceVersion() {
        return resourceVersion;
    }

    /**
     * Sets the value of the resourceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceVersion(String value) {
        this.resourceVersion = value;
    }

    /**
     * Gets the value of the volumeGroups property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeGroups }
     *     
     */
    public VolumeGroups getVolumeGroups() {
        return volumeGroups;
    }

    /**
     * Sets the value of the volumeGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeGroups }
     *     
     */
    public void setVolumeGroups(VolumeGroups value) {
        this.volumeGroups = value;
    }

    /**
     * Gets the value of the tenants property.
     * 
     * @return
     *     possible object is
     *     {@link Tenants }
     *     
     */
    public Tenants getTenants() {
        return tenants;
    }

    /**
     * Sets the value of the tenants property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tenants }
     *     
     */
    public void setTenants(Tenants value) {
        this.tenants = value;
    }

    /**
     * Gets the value of the flavors property.
     * 
     * @return
     *     possible object is
     *     {@link Flavors }
     *     
     */
    public Flavors getFlavors() {
        return flavors;
    }

    /**
     * Sets the value of the flavors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flavors }
     *     
     */
    public void setFlavors(Flavors value) {
        this.flavors = value;
    }

    /**
     * Gets the value of the groupAssignments property.
     * 
     * @return
     *     possible object is
     *     {@link GroupAssignments }
     *     
     */
    public GroupAssignments getGroupAssignments() {
        return groupAssignments;
    }

    /**
     * Sets the value of the groupAssignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupAssignments }
     *     
     */
    public void setGroupAssignments(GroupAssignments value) {
        this.groupAssignments = value;
    }

    /**
     * Gets the value of the snapshots property.
     * 
     * @return
     *     possible object is
     *     {@link Snapshots }
     *     
     */
    public Snapshots getSnapshots() {
        return snapshots;
    }

    /**
     * Sets the value of the snapshots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Snapshots }
     *     
     */
    public void setSnapshots(Snapshots value) {
        this.snapshots = value;
    }

    /**
     * Gets the value of the images property.
     * 
     * @return
     *     possible object is
     *     {@link Images }
     *     
     */
    public Images getImages() {
        return images;
    }

    /**
     * Sets the value of the images property.
     * 
     * @param value
     *     allowed object is
     *     {@link Images }
     *     
     */
    public void setImages(Images value) {
        this.images = value;
    }

    /**
     * Gets the value of the availabilityZones property.
     * 
     * @return
     *     possible object is
     *     {@link AvailabilityZones }
     *     
     */
    public AvailabilityZones getAvailabilityZones() {
        return availabilityZones;
    }

    /**
     * Sets the value of the availabilityZones property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailabilityZones }
     *     
     */
    public void setAvailabilityZones(AvailabilityZones value) {
        this.availabilityZones = value;
    }

    /**
     * Gets the value of the relationshipList property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipList }
     *     
     */
    public RelationshipList getRelationshipList() {
        return relationshipList;
    }

    /**
     * Sets the value of the relationshipList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipList }
     *     
     */
    public void setRelationshipList(RelationshipList value) {
        this.relationshipList = value;
    }

}
