//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.14 at 01:05:25 PM EST 
//


package org.openecomp.aai.inventory.v8;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}cloud-regions" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}pservers" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cloudRegions",
    "pservers"
})
@XmlRootElement(name = "cloud-infrastructure")
public class CloudInfrastructure
    implements AAIDatum
{

    @XmlElement(name = "cloud-regions")
    protected CloudRegions cloudRegions;
    protected Pservers pservers;

    /**
     * Gets the value of the cloudRegions property.
     * 
     * @return
     *     possible object is
     *     {@link CloudRegions }
     *     
     */
    public CloudRegions getCloudRegions() {
        return cloudRegions;
    }

    /**
     * Sets the value of the cloudRegions property.
     * 
     * @param value
     *     allowed object is
     *     {@link CloudRegions }
     *     
     */
    public void setCloudRegions(CloudRegions value) {
        this.cloudRegions = value;
    }

    /**
     * Gets the value of the pservers property.
     * 
     * @return
     *     possible object is
     *     {@link Pservers }
     *     
     */
    public Pservers getPservers() {
        return pservers;
    }

    /**
     * Sets the value of the pservers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pservers }
     *     
     */
    public void setPservers(Pservers value) {
        this.pservers = value;
    }

}
