//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.20 at 02:31:54 PM EST 
//


package org.openecomp.aai.inventory.v8;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="edgeLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="multiplicityRule" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="isParent" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="usesResource" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="hasDelTarget" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="SVC-INFRA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SVC-INFRA-REV" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "edgeLabel",
    "direction",
    "multiplicityRule",
    "isParent",
    "usesResource",
    "hasDelTarget",
    "svcinfra",
    "svcinfrarev"
})
@XmlRootElement(name = "edge-prop-names")
public class EdgePropNames
    implements AAIDatum
{

    protected String edgeLabel;
    protected String direction;
    protected String multiplicityRule;
    protected Boolean isParent;
    protected Boolean usesResource;
    protected Boolean hasDelTarget;
    @XmlElement(name = "SVC-INFRA")
    protected String svcinfra;
    @XmlElement(name = "SVC-INFRA-REV")
    protected String svcinfrarev;

    /**
     * Gets the value of the edgeLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdgeLabel() {
        return edgeLabel;
    }

    /**
     * Sets the value of the edgeLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdgeLabel(String value) {
        this.edgeLabel = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }

    /**
     * Gets the value of the multiplicityRule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultiplicityRule() {
        return multiplicityRule;
    }

    /**
     * Sets the value of the multiplicityRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultiplicityRule(String value) {
        this.multiplicityRule = value;
    }

    /**
     * Gets the value of the isParent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsParent() {
        return isParent;
    }

    /**
     * Sets the value of the isParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsParent(Boolean value) {
        this.isParent = value;
    }

    /**
     * Gets the value of the usesResource property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsesResource() {
        return usesResource;
    }

    /**
     * Sets the value of the usesResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsesResource(Boolean value) {
        this.usesResource = value;
    }

    /**
     * Gets the value of the hasDelTarget property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasDelTarget() {
        return hasDelTarget;
    }

    /**
     * Sets the value of the hasDelTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasDelTarget(Boolean value) {
        this.hasDelTarget = value;
    }

    /**
     * Gets the value of the svcinfra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSVCINFRA() {
        return svcinfra;
    }

    /**
     * Sets the value of the svcinfra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSVCINFRA(String value) {
        this.svcinfra = value;
    }

    /**
     * Gets the value of the svcinfrarev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSVCINFRAREV() {
        return svcinfrarev;
    }

    /**
     * Sets the value of the svcinfrarev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSVCINFRAREV(String value) {
        this.svcinfrarev = value;
    }

}
