//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.20 at 02:31:54 PM EST 
//


package org.openecomp.aai.inventory.v8;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="element-choice-set-uuid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="element-choice-set-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cardinality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resource-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}model-elements" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}relationship-list" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "elementChoiceSetUuid",
    "elementChoiceSetName",
    "cardinality",
    "resourceVersion",
    "modelElements",
    "relationshipList"
})
@XmlRootElement(name = "element-choice-set")
public class ElementChoiceSet
    implements AAIDatum
{

    @XmlElement(name = "element-choice-set-uuid", required = true)
    protected String elementChoiceSetUuid;
    @XmlElement(name = "element-choice-set-name", required = true)
    protected String elementChoiceSetName;
    protected String cardinality;
    @XmlElement(name = "resource-version")
    protected String resourceVersion;
    @XmlElement(name = "model-elements")
    protected ModelElements modelElements;
    @XmlElement(name = "relationship-list")
    protected RelationshipList relationshipList;

    /**
     * Gets the value of the elementChoiceSetUuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementChoiceSetUuid() {
        return elementChoiceSetUuid;
    }

    /**
     * Sets the value of the elementChoiceSetUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementChoiceSetUuid(String value) {
        this.elementChoiceSetUuid = value;
    }

    /**
     * Gets the value of the elementChoiceSetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementChoiceSetName() {
        return elementChoiceSetName;
    }

    /**
     * Sets the value of the elementChoiceSetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementChoiceSetName(String value) {
        this.elementChoiceSetName = value;
    }

    /**
     * Gets the value of the cardinality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardinality() {
        return cardinality;
    }

    /**
     * Sets the value of the cardinality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardinality(String value) {
        this.cardinality = value;
    }

    /**
     * Gets the value of the resourceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceVersion() {
        return resourceVersion;
    }

    /**
     * Sets the value of the resourceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceVersion(String value) {
        this.resourceVersion = value;
    }

    /**
     * Gets the value of the modelElements property.
     * 
     * @return
     *     possible object is
     *     {@link ModelElements }
     *     
     */
    public ModelElements getModelElements() {
        return modelElements;
    }

    /**
     * Sets the value of the modelElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelElements }
     *     
     */
    public void setModelElements(ModelElements value) {
        this.modelElements = value;
    }

    /**
     * Gets the value of the relationshipList property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipList }
     *     
     */
    public RelationshipList getRelationshipList() {
        return relationshipList;
    }

    /**
     * Sets the value of the relationshipList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipList }
     *     
     */
    public void setRelationshipList(RelationshipList value) {
        this.relationshipList = value;
    }

}
