//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.20 at 02:31:54 PM EST 
//


package org.openecomp.aai.inventory.v8;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="vnf-id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="vnf-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="vnf-name2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vnf-type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="service-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="regional-resource-zone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="prov-status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="operational-state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="license-key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="equipment-role" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="orchestration-status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="heat-stack-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mso-catalog-key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="management-option" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ipv4-oam-address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ipv4-loopback0-address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="nm-lan-v6-address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="management-v6-address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vcpu" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="vcpu-units" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vmemory" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="vmemory-units" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vdisk" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="vdisk-units" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="in-maint" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="is-closed-loop-disabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="resource-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="summary-status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="encrypted-access-flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="entitlement-assignment-group-uuid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="entitlement-resource-uuid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="license-assignment-group-uuid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="license-key-uuid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="persona-model-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="persona-model-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="persona-model-customization-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="widget-model-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="widget-model-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="as-number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="regional-resource-subzone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}relationship-list" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}l-interfaces" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}lag-interfaces" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}vf-modules" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vnfId",
    "vnfName",
    "vnfName2",
    "vnfType",
    "serviceId",
    "regionalResourceZone",
    "provStatus",
    "operationalState",
    "licenseKey",
    "equipmentRole",
    "orchestrationStatus",
    "heatStackId",
    "msoCatalogKey",
    "managementOption",
    "ipv4OamAddress",
    "ipv4Loopback0Address",
    "nmLanV6Address",
    "managementV6Address",
    "vcpu",
    "vcpuUnits",
    "vmemory",
    "vmemoryUnits",
    "vdisk",
    "vdiskUnits",
    "inMaint",
    "isClosedLoopDisabled",
    "resourceVersion",
    "summaryStatus",
    "encryptedAccessFlag",
    "entitlementAssignmentGroupUuid",
    "entitlementResourceUuid",
    "licenseAssignmentGroupUuid",
    "licenseKeyUuid",
    "personaModelId",
    "personaModelVersion",
    "personaModelCustomizationId",
    "widgetModelId",
    "widgetModelVersion",
    "asNumber",
    "regionalResourceSubzone",
    "relationshipList",
    "lInterfaces",
    "lagInterfaces",
    "vfModules"
})
@XmlRootElement(name = "generic-vnf")
public class GenericVnf
    implements AAIDatum
{

    @XmlElement(name = "vnf-id", required = true)
    protected String vnfId;
    @XmlElement(name = "vnf-name", required = true)
    protected String vnfName;
    @XmlElement(name = "vnf-name2")
    protected String vnfName2;
    @XmlElement(name = "vnf-type", required = true)
    protected String vnfType;
    @XmlElement(name = "service-id")
    protected String serviceId;
    @XmlElement(name = "regional-resource-zone")
    protected String regionalResourceZone;
    @XmlElement(name = "prov-status")
    protected String provStatus;
    @XmlElement(name = "operational-state")
    protected String operationalState;
    @XmlElement(name = "license-key")
    protected String licenseKey;
    @XmlElement(name = "equipment-role")
    protected String equipmentRole;
    @XmlElement(name = "orchestration-status")
    protected String orchestrationStatus;
    @XmlElement(name = "heat-stack-id")
    protected String heatStackId;
    @XmlElement(name = "mso-catalog-key")
    protected String msoCatalogKey;
    @XmlElement(name = "management-option")
    protected String managementOption;
    @XmlElement(name = "ipv4-oam-address")
    protected String ipv4OamAddress;
    @XmlElement(name = "ipv4-loopback0-address")
    protected String ipv4Loopback0Address;
    @XmlElement(name = "nm-lan-v6-address")
    protected String nmLanV6Address;
    @XmlElement(name = "management-v6-address")
    protected String managementV6Address;
    @XmlSchemaType(name = "unsignedInt")
    protected Long vcpu;
    @XmlElement(name = "vcpu-units")
    protected String vcpuUnits;
    @XmlSchemaType(name = "unsignedInt")
    protected Long vmemory;
    @XmlElement(name = "vmemory-units")
    protected String vmemoryUnits;
    @XmlSchemaType(name = "unsignedInt")
    protected Long vdisk;
    @XmlElement(name = "vdisk-units")
    protected String vdiskUnits;
    @XmlElement(name = "in-maint")
    protected boolean inMaint;
    @XmlElement(name = "is-closed-loop-disabled")
    protected boolean isClosedLoopDisabled;
    @XmlElement(name = "resource-version")
    protected String resourceVersion;
    @XmlElement(name = "summary-status")
    protected String summaryStatus;
    @XmlElement(name = "encrypted-access-flag")
    protected Boolean encryptedAccessFlag;
    @XmlElement(name = "entitlement-assignment-group-uuid")
    protected String entitlementAssignmentGroupUuid;
    @XmlElement(name = "entitlement-resource-uuid")
    protected String entitlementResourceUuid;
    @XmlElement(name = "license-assignment-group-uuid")
    protected String licenseAssignmentGroupUuid;
    @XmlElement(name = "license-key-uuid")
    protected String licenseKeyUuid;
    @XmlElement(name = "persona-model-id")
    protected String personaModelId;
    @XmlElement(name = "persona-model-version")
    protected String personaModelVersion;
    @XmlElement(name = "persona-model-customization-id")
    protected String personaModelCustomizationId;
    @XmlElement(name = "widget-model-id")
    protected String widgetModelId;
    @XmlElement(name = "widget-model-version")
    protected String widgetModelVersion;
    @XmlElement(name = "as-number")
    protected String asNumber;
    @XmlElement(name = "regional-resource-subzone")
    protected String regionalResourceSubzone;
    @XmlElement(name = "relationship-list")
    protected RelationshipList relationshipList;
    @XmlElement(name = "l-interfaces")
    protected LInterfaces lInterfaces;
    @XmlElement(name = "lag-interfaces")
    protected LagInterfaces lagInterfaces;
    @XmlElement(name = "vf-modules")
    protected VfModules vfModules;

    /**
     * Gets the value of the vnfId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVnfId() {
        return vnfId;
    }

    /**
     * Sets the value of the vnfId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVnfId(String value) {
        this.vnfId = value;
    }

    /**
     * Gets the value of the vnfName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVnfName() {
        return vnfName;
    }

    /**
     * Sets the value of the vnfName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVnfName(String value) {
        this.vnfName = value;
    }

    /**
     * Gets the value of the vnfName2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVnfName2() {
        return vnfName2;
    }

    /**
     * Sets the value of the vnfName2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVnfName2(String value) {
        this.vnfName2 = value;
    }

    /**
     * Gets the value of the vnfType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVnfType() {
        return vnfType;
    }

    /**
     * Sets the value of the vnfType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVnfType(String value) {
        this.vnfType = value;
    }

    /**
     * Gets the value of the serviceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * Sets the value of the serviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceId(String value) {
        this.serviceId = value;
    }

    /**
     * Gets the value of the regionalResourceZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionalResourceZone() {
        return regionalResourceZone;
    }

    /**
     * Sets the value of the regionalResourceZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionalResourceZone(String value) {
        this.regionalResourceZone = value;
    }

    /**
     * Gets the value of the provStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvStatus() {
        return provStatus;
    }

    /**
     * Sets the value of the provStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvStatus(String value) {
        this.provStatus = value;
    }

    /**
     * Gets the value of the operationalState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationalState() {
        return operationalState;
    }

    /**
     * Sets the value of the operationalState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationalState(String value) {
        this.operationalState = value;
    }

    /**
     * Gets the value of the licenseKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseKey() {
        return licenseKey;
    }

    /**
     * Sets the value of the licenseKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseKey(String value) {
        this.licenseKey = value;
    }

    /**
     * Gets the value of the equipmentRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentRole() {
        return equipmentRole;
    }

    /**
     * Sets the value of the equipmentRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentRole(String value) {
        this.equipmentRole = value;
    }

    /**
     * Gets the value of the orchestrationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrchestrationStatus() {
        return orchestrationStatus;
    }

    /**
     * Sets the value of the orchestrationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrchestrationStatus(String value) {
        this.orchestrationStatus = value;
    }

    /**
     * Gets the value of the heatStackId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeatStackId() {
        return heatStackId;
    }

    /**
     * Sets the value of the heatStackId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeatStackId(String value) {
        this.heatStackId = value;
    }

    /**
     * Gets the value of the msoCatalogKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsoCatalogKey() {
        return msoCatalogKey;
    }

    /**
     * Sets the value of the msoCatalogKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsoCatalogKey(String value) {
        this.msoCatalogKey = value;
    }

    /**
     * Gets the value of the managementOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagementOption() {
        return managementOption;
    }

    /**
     * Sets the value of the managementOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagementOption(String value) {
        this.managementOption = value;
    }

    /**
     * Gets the value of the ipv4OamAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpv4OamAddress() {
        return ipv4OamAddress;
    }

    /**
     * Sets the value of the ipv4OamAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpv4OamAddress(String value) {
        this.ipv4OamAddress = value;
    }

    /**
     * Gets the value of the ipv4Loopback0Address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpv4Loopback0Address() {
        return ipv4Loopback0Address;
    }

    /**
     * Sets the value of the ipv4Loopback0Address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpv4Loopback0Address(String value) {
        this.ipv4Loopback0Address = value;
    }

    /**
     * Gets the value of the nmLanV6Address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmLanV6Address() {
        return nmLanV6Address;
    }

    /**
     * Sets the value of the nmLanV6Address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmLanV6Address(String value) {
        this.nmLanV6Address = value;
    }

    /**
     * Gets the value of the managementV6Address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagementV6Address() {
        return managementV6Address;
    }

    /**
     * Sets the value of the managementV6Address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagementV6Address(String value) {
        this.managementV6Address = value;
    }

    /**
     * Gets the value of the vcpu property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVcpu() {
        return vcpu;
    }

    /**
     * Sets the value of the vcpu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVcpu(Long value) {
        this.vcpu = value;
    }

    /**
     * Gets the value of the vcpuUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVcpuUnits() {
        return vcpuUnits;
    }

    /**
     * Sets the value of the vcpuUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVcpuUnits(String value) {
        this.vcpuUnits = value;
    }

    /**
     * Gets the value of the vmemory property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVmemory() {
        return vmemory;
    }

    /**
     * Sets the value of the vmemory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVmemory(Long value) {
        this.vmemory = value;
    }

    /**
     * Gets the value of the vmemoryUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVmemoryUnits() {
        return vmemoryUnits;
    }

    /**
     * Sets the value of the vmemoryUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVmemoryUnits(String value) {
        this.vmemoryUnits = value;
    }

    /**
     * Gets the value of the vdisk property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVdisk() {
        return vdisk;
    }

    /**
     * Sets the value of the vdisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVdisk(Long value) {
        this.vdisk = value;
    }

    /**
     * Gets the value of the vdiskUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVdiskUnits() {
        return vdiskUnits;
    }

    /**
     * Sets the value of the vdiskUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVdiskUnits(String value) {
        this.vdiskUnits = value;
    }

    /**
     * Gets the value of the inMaint property.
     * 
     */
    public boolean isInMaint() {
        return inMaint;
    }

    /**
     * Sets the value of the inMaint property.
     * 
     */
    public void setInMaint(boolean value) {
        this.inMaint = value;
    }

    /**
     * Gets the value of the isClosedLoopDisabled property.
     * 
     */
    public boolean isIsClosedLoopDisabled() {
        return isClosedLoopDisabled;
    }

    /**
     * Sets the value of the isClosedLoopDisabled property.
     * 
     */
    public void setIsClosedLoopDisabled(boolean value) {
        this.isClosedLoopDisabled = value;
    }

    /**
     * Gets the value of the resourceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceVersion() {
        return resourceVersion;
    }

    /**
     * Sets the value of the resourceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceVersion(String value) {
        this.resourceVersion = value;
    }

    /**
     * Gets the value of the summaryStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummaryStatus() {
        return summaryStatus;
    }

    /**
     * Sets the value of the summaryStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummaryStatus(String value) {
        this.summaryStatus = value;
    }

    /**
     * Gets the value of the encryptedAccessFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEncryptedAccessFlag() {
        return encryptedAccessFlag;
    }

    /**
     * Sets the value of the encryptedAccessFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEncryptedAccessFlag(Boolean value) {
        this.encryptedAccessFlag = value;
    }

    /**
     * Gets the value of the entitlementAssignmentGroupUuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntitlementAssignmentGroupUuid() {
        return entitlementAssignmentGroupUuid;
    }

    /**
     * Sets the value of the entitlementAssignmentGroupUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntitlementAssignmentGroupUuid(String value) {
        this.entitlementAssignmentGroupUuid = value;
    }

    /**
     * Gets the value of the entitlementResourceUuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntitlementResourceUuid() {
        return entitlementResourceUuid;
    }

    /**
     * Sets the value of the entitlementResourceUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntitlementResourceUuid(String value) {
        this.entitlementResourceUuid = value;
    }

    /**
     * Gets the value of the licenseAssignmentGroupUuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseAssignmentGroupUuid() {
        return licenseAssignmentGroupUuid;
    }

    /**
     * Sets the value of the licenseAssignmentGroupUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseAssignmentGroupUuid(String value) {
        this.licenseAssignmentGroupUuid = value;
    }

    /**
     * Gets the value of the licenseKeyUuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseKeyUuid() {
        return licenseKeyUuid;
    }

    /**
     * Sets the value of the licenseKeyUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseKeyUuid(String value) {
        this.licenseKeyUuid = value;
    }

    /**
     * Gets the value of the personaModelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonaModelId() {
        return personaModelId;
    }

    /**
     * Sets the value of the personaModelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonaModelId(String value) {
        this.personaModelId = value;
    }

    /**
     * Gets the value of the personaModelVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonaModelVersion() {
        return personaModelVersion;
    }

    /**
     * Sets the value of the personaModelVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonaModelVersion(String value) {
        this.personaModelVersion = value;
    }

    /**
     * Gets the value of the personaModelCustomizationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonaModelCustomizationId() {
        return personaModelCustomizationId;
    }

    /**
     * Sets the value of the personaModelCustomizationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonaModelCustomizationId(String value) {
        this.personaModelCustomizationId = value;
    }

    /**
     * Gets the value of the widgetModelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidgetModelId() {
        return widgetModelId;
    }

    /**
     * Sets the value of the widgetModelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidgetModelId(String value) {
        this.widgetModelId = value;
    }

    /**
     * Gets the value of the widgetModelVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidgetModelVersion() {
        return widgetModelVersion;
    }

    /**
     * Sets the value of the widgetModelVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidgetModelVersion(String value) {
        this.widgetModelVersion = value;
    }

    /**
     * Gets the value of the asNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAsNumber() {
        return asNumber;
    }

    /**
     * Sets the value of the asNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAsNumber(String value) {
        this.asNumber = value;
    }

    /**
     * Gets the value of the regionalResourceSubzone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionalResourceSubzone() {
        return regionalResourceSubzone;
    }

    /**
     * Sets the value of the regionalResourceSubzone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionalResourceSubzone(String value) {
        this.regionalResourceSubzone = value;
    }

    /**
     * Gets the value of the relationshipList property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipList }
     *     
     */
    public RelationshipList getRelationshipList() {
        return relationshipList;
    }

    /**
     * Sets the value of the relationshipList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipList }
     *     
     */
    public void setRelationshipList(RelationshipList value) {
        this.relationshipList = value;
    }

    /**
     * Gets the value of the lInterfaces property.
     * 
     * @return
     *     possible object is
     *     {@link LInterfaces }
     *     
     */
    public LInterfaces getLInterfaces() {
        return lInterfaces;
    }

    /**
     * Sets the value of the lInterfaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link LInterfaces }
     *     
     */
    public void setLInterfaces(LInterfaces value) {
        this.lInterfaces = value;
    }

    /**
     * Gets the value of the lagInterfaces property.
     * 
     * @return
     *     possible object is
     *     {@link LagInterfaces }
     *     
     */
    public LagInterfaces getLagInterfaces() {
        return lagInterfaces;
    }

    /**
     * Sets the value of the lagInterfaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link LagInterfaces }
     *     
     */
    public void setLagInterfaces(LagInterfaces value) {
        this.lagInterfaces = value;
    }

    /**
     * Gets the value of the vfModules property.
     * 
     * @return
     *     possible object is
     *     {@link VfModules }
     *     
     */
    public VfModules getVfModules() {
        return vfModules;
    }

    /**
     * Sets the value of the vfModules property.
     * 
     * @param value
     *     allowed object is
     *     {@link VfModules }
     *     
     */
    public void setVfModules(VfModules value) {
        this.vfModules = value;
    }

}
