//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 07:59:51 PM EST 
//


package org.openecomp.aai.inventory.v8;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="image-id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="image-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="image-architecture" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="image-os-distro" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="image-os-version" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="application" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="application-vendor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="application-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="image-selflink" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="resource-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}relationship-list" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}metadata" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imageId",
    "imageName",
    "imageArchitecture",
    "imageOsDistro",
    "imageOsVersion",
    "application",
    "applicationVendor",
    "applicationVersion",
    "imageSelflink",
    "resourceVersion",
    "relationshipList",
    "metadata"
})
@XmlRootElement(name = "image")
public class Image
    implements AAIDatum
{

    @XmlElement(name = "image-id", required = true)
    protected String imageId;
    @XmlElement(name = "image-name", required = true)
    protected String imageName;
    @XmlElement(name = "image-architecture")
    protected String imageArchitecture;
    @XmlElement(name = "image-os-distro", required = true)
    protected String imageOsDistro;
    @XmlElement(name = "image-os-version", required = true)
    protected String imageOsVersion;
    protected String application;
    @XmlElement(name = "application-vendor")
    protected String applicationVendor;
    @XmlElement(name = "application-version")
    protected String applicationVersion;
    @XmlElement(name = "image-selflink", required = true)
    protected String imageSelflink;
    @XmlElement(name = "resource-version")
    protected String resourceVersion;
    @XmlElement(name = "relationship-list")
    protected RelationshipList relationshipList;
    protected Metadata metadata;

    /**
     * Gets the value of the imageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * Sets the value of the imageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageId(String value) {
        this.imageId = value;
    }

    /**
     * Gets the value of the imageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * Sets the value of the imageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageName(String value) {
        this.imageName = value;
    }

    /**
     * Gets the value of the imageArchitecture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageArchitecture() {
        return imageArchitecture;
    }

    /**
     * Sets the value of the imageArchitecture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageArchitecture(String value) {
        this.imageArchitecture = value;
    }

    /**
     * Gets the value of the imageOsDistro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageOsDistro() {
        return imageOsDistro;
    }

    /**
     * Sets the value of the imageOsDistro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageOsDistro(String value) {
        this.imageOsDistro = value;
    }

    /**
     * Gets the value of the imageOsVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageOsVersion() {
        return imageOsVersion;
    }

    /**
     * Sets the value of the imageOsVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageOsVersion(String value) {
        this.imageOsVersion = value;
    }

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplication(String value) {
        this.application = value;
    }

    /**
     * Gets the value of the applicationVendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationVendor() {
        return applicationVendor;
    }

    /**
     * Sets the value of the applicationVendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationVendor(String value) {
        this.applicationVendor = value;
    }

    /**
     * Gets the value of the applicationVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationVersion() {
        return applicationVersion;
    }

    /**
     * Sets the value of the applicationVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationVersion(String value) {
        this.applicationVersion = value;
    }

    /**
     * Gets the value of the imageSelflink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageSelflink() {
        return imageSelflink;
    }

    /**
     * Sets the value of the imageSelflink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageSelflink(String value) {
        this.imageSelflink = value;
    }

    /**
     * Gets the value of the resourceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceVersion() {
        return resourceVersion;
    }

    /**
     * Sets the value of the resourceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceVersion(String value) {
        this.resourceVersion = value;
    }

    /**
     * Gets the value of the relationshipList property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipList }
     *     
     */
    public RelationshipList getRelationshipList() {
        return relationshipList;
    }

    /**
     * Sets the value of the relationshipList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipList }
     *     
     */
    public void setRelationshipList(RelationshipList value) {
        this.relationshipList = value;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link Metadata }
     *     
     */
    public Metadata getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Metadata }
     *     
     */
    public void setMetadata(Metadata value) {
        this.metadata = value;
    }

}
