//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 08:44:52 AM EST 
//


package org.openecomp.aai.inventory.v8;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}search" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}actions" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}cloud-infrastructure" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}business" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}service-design-and-creation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}network" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}aai-internal" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "search",
    "actions",
    "cloudInfrastructure",
    "business",
    "serviceDesignAndCreation",
    "network",
    "aaiInternal"
})
@XmlRootElement(name = "inventory")
public class Inventory
    implements AAIDatum
{

    protected Search search;
    protected Actions actions;
    @XmlElement(name = "cloud-infrastructure")
    protected CloudInfrastructure cloudInfrastructure;
    protected Business business;
    @XmlElement(name = "service-design-and-creation")
    protected ServiceDesignAndCreation serviceDesignAndCreation;
    protected Network network;
    @XmlElement(name = "aai-internal")
    protected AaiInternal aaiInternal;

    /**
     * Gets the value of the search property.
     * 
     * @return
     *     possible object is
     *     {@link Search }
     *     
     */
    public Search getSearch() {
        return search;
    }

    /**
     * Sets the value of the search property.
     * 
     * @param value
     *     allowed object is
     *     {@link Search }
     *     
     */
    public void setSearch(Search value) {
        this.search = value;
    }

    /**
     * Gets the value of the actions property.
     * 
     * @return
     *     possible object is
     *     {@link Actions }
     *     
     */
    public Actions getActions() {
        return actions;
    }

    /**
     * Sets the value of the actions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Actions }
     *     
     */
    public void setActions(Actions value) {
        this.actions = value;
    }

    /**
     * Gets the value of the cloudInfrastructure property.
     * 
     * @return
     *     possible object is
     *     {@link CloudInfrastructure }
     *     
     */
    public CloudInfrastructure getCloudInfrastructure() {
        return cloudInfrastructure;
    }

    /**
     * Sets the value of the cloudInfrastructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link CloudInfrastructure }
     *     
     */
    public void setCloudInfrastructure(CloudInfrastructure value) {
        this.cloudInfrastructure = value;
    }

    /**
     * Gets the value of the business property.
     * 
     * @return
     *     possible object is
     *     {@link Business }
     *     
     */
    public Business getBusiness() {
        return business;
    }

    /**
     * Sets the value of the business property.
     * 
     * @param value
     *     allowed object is
     *     {@link Business }
     *     
     */
    public void setBusiness(Business value) {
        this.business = value;
    }

    /**
     * Gets the value of the serviceDesignAndCreation property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceDesignAndCreation }
     *     
     */
    public ServiceDesignAndCreation getServiceDesignAndCreation() {
        return serviceDesignAndCreation;
    }

    /**
     * Sets the value of the serviceDesignAndCreation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceDesignAndCreation }
     *     
     */
    public void setServiceDesignAndCreation(ServiceDesignAndCreation value) {
        this.serviceDesignAndCreation = value;
    }

    /**
     * Gets the value of the network property.
     * 
     * @return
     *     possible object is
     *     {@link Network }
     *     
     */
    public Network getNetwork() {
        return network;
    }

    /**
     * Sets the value of the network property.
     * 
     * @param value
     *     allowed object is
     *     {@link Network }
     *     
     */
    public void setNetwork(Network value) {
        this.network = value;
    }

    /**
     * Gets the value of the aaiInternal property.
     * 
     * @return
     *     possible object is
     *     {@link AaiInternal }
     *     
     */
    public AaiInternal getAaiInternal() {
        return aaiInternal;
    }

    /**
     * Sets the value of the aaiInternal property.
     * 
     * @param value
     *     allowed object is
     *     {@link AaiInternal }
     *     
     */
    public void setAaiInternal(AaiInternal value) {
        this.aaiInternal = value;
    }

}
