//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 07:59:51 PM EST 
//


package org.openecomp.aai.inventory.v8;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="inventory-item-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="inventory-item-link" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}inventory-item-data" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}tagged-inventory-item-list" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inventoryItemType",
    "inventoryItemLink",
    "inventoryItemData",
    "taggedInventoryItemList"
})
@XmlRootElement(name = "inventory-item")
public class InventoryItem
    implements AAIDatum
{

    @XmlElement(name = "inventory-item-type")
    protected String inventoryItemType;
    @XmlElement(name = "inventory-item-link")
    protected String inventoryItemLink;
    @XmlElement(name = "inventory-item-data")
    protected List<InventoryItemData> inventoryItemData;
    @XmlElement(name = "tagged-inventory-item-list")
    protected List<TaggedInventoryItemList> taggedInventoryItemList;

    /**
     * Gets the value of the inventoryItemType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryItemType() {
        return inventoryItemType;
    }

    /**
     * Sets the value of the inventoryItemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryItemType(String value) {
        this.inventoryItemType = value;
    }

    /**
     * Gets the value of the inventoryItemLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryItemLink() {
        return inventoryItemLink;
    }

    /**
     * Sets the value of the inventoryItemLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryItemLink(String value) {
        this.inventoryItemLink = value;
    }

    /**
     * Gets the value of the inventoryItemData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inventoryItemData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInventoryItemData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InventoryItemData }
     * 
     * 
     */
    public List<InventoryItemData> getInventoryItemData() {
        if (inventoryItemData == null) {
            inventoryItemData = new ArrayList<InventoryItemData>();
        }
        return this.inventoryItemData;
    }

    /**
     * Gets the value of the taggedInventoryItemList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taggedInventoryItemList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaggedInventoryItemList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaggedInventoryItemList }
     * 
     * 
     */
    public List<TaggedInventoryItemList> getTaggedInventoryItemList() {
        if (taggedInventoryItemList == null) {
            taggedInventoryItemList = new ArrayList<TaggedInventoryItemList>();
        }
        return this.taggedInventoryItemList;
    }

}
