//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.19 at 04:48:44 PM EST 
//


package org.openecomp.aai.inventory.v8;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="l3-interface-ipv4-address" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="l3-interface-ipv4-prefix-length" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="vlan-id-inner" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="vlan-id-outer" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="is-floating" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="resource-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="neutron-network-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="neutron-subnet-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}relationship-list" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "l3InterfaceIpv4Address",
    "l3InterfaceIpv4PrefixLength",
    "vlanIdInner",
    "vlanIdOuter",
    "isFloating",
    "resourceVersion",
    "neutronNetworkId",
    "neutronSubnetId",
    "relationshipList"
})
@XmlRootElement(name = "l3-interface-ipv4-address-list")
public class L3InterfaceIpv4AddressList
    implements AAIDatum
{

    @XmlElement(name = "l3-interface-ipv4-address", required = true)
    protected String l3InterfaceIpv4Address;
    @XmlElement(name = "l3-interface-ipv4-prefix-length")
    @XmlSchemaType(name = "unsignedInt")
    protected Long l3InterfaceIpv4PrefixLength;
    @XmlElement(name = "vlan-id-inner")
    @XmlSchemaType(name = "unsignedInt")
    protected Long vlanIdInner;
    @XmlElement(name = "vlan-id-outer")
    @XmlSchemaType(name = "unsignedInt")
    protected Long vlanIdOuter;
    @XmlElement(name = "is-floating")
    protected Boolean isFloating;
    @XmlElement(name = "resource-version")
    protected String resourceVersion;
    @XmlElement(name = "neutron-network-id")
    protected String neutronNetworkId;
    @XmlElement(name = "neutron-subnet-id")
    protected String neutronSubnetId;
    @XmlElement(name = "relationship-list")
    protected RelationshipList relationshipList;

    /**
     * Gets the value of the l3InterfaceIpv4Address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getL3InterfaceIpv4Address() {
        return l3InterfaceIpv4Address;
    }

    /**
     * Sets the value of the l3InterfaceIpv4Address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setL3InterfaceIpv4Address(String value) {
        this.l3InterfaceIpv4Address = value;
    }

    /**
     * Gets the value of the l3InterfaceIpv4PrefixLength property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getL3InterfaceIpv4PrefixLength() {
        return l3InterfaceIpv4PrefixLength;
    }

    /**
     * Sets the value of the l3InterfaceIpv4PrefixLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setL3InterfaceIpv4PrefixLength(Long value) {
        this.l3InterfaceIpv4PrefixLength = value;
    }

    /**
     * Gets the value of the vlanIdInner property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVlanIdInner() {
        return vlanIdInner;
    }

    /**
     * Sets the value of the vlanIdInner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVlanIdInner(Long value) {
        this.vlanIdInner = value;
    }

    /**
     * Gets the value of the vlanIdOuter property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVlanIdOuter() {
        return vlanIdOuter;
    }

    /**
     * Sets the value of the vlanIdOuter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVlanIdOuter(Long value) {
        this.vlanIdOuter = value;
    }

    /**
     * Gets the value of the isFloating property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsFloating() {
        return isFloating;
    }

    /**
     * Sets the value of the isFloating property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsFloating(Boolean value) {
        this.isFloating = value;
    }

    /**
     * Gets the value of the resourceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceVersion() {
        return resourceVersion;
    }

    /**
     * Sets the value of the resourceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceVersion(String value) {
        this.resourceVersion = value;
    }

    /**
     * Gets the value of the neutronNetworkId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeutronNetworkId() {
        return neutronNetworkId;
    }

    /**
     * Sets the value of the neutronNetworkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeutronNetworkId(String value) {
        this.neutronNetworkId = value;
    }

    /**
     * Gets the value of the neutronSubnetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeutronSubnetId() {
        return neutronSubnetId;
    }

    /**
     * Sets the value of the neutronSubnetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeutronSubnetId(String value) {
        this.neutronSubnetId = value;
    }

    /**
     * Gets the value of the relationshipList property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipList }
     *     
     */
    public RelationshipList getRelationshipList() {
        return relationshipList;
    }

    /**
     * Sets the value of the relationshipList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipList }
     *     
     */
    public void setRelationshipList(RelationshipList value) {
        this.relationshipList = value;
    }

}
