//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 08:44:52 AM EST 
//


package org.openecomp.aai.inventory.v8;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="network-id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="network-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="network-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="network-role" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="network-technology" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="neutron-network-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="is-bound-to-vpn" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="service-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="network-role-instance" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="resource-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="orchestration-status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="heat-stack-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mso-catalog-key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="contrail-network-fqdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="persona-model-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="persona-model-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="widget-model-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="widget-model-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="physical-network-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="is-provider-network" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="is-shared-network" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="is-external-network" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}subnets" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}ctag-assignments" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}segmentation-assignments" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}relationship-list" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "networkId",
    "networkName",
    "networkType",
    "networkRole",
    "networkTechnology",
    "neutronNetworkId",
    "isBoundToVpn",
    "serviceId",
    "networkRoleInstance",
    "resourceVersion",
    "orchestrationStatus",
    "heatStackId",
    "msoCatalogKey",
    "contrailNetworkFqdn",
    "personaModelId",
    "personaModelVersion",
    "widgetModelId",
    "widgetModelVersion",
    "physicalNetworkName",
    "isProviderNetwork",
    "isSharedNetwork",
    "isExternalNetwork",
    "subnets",
    "ctagAssignments",
    "segmentationAssignments",
    "relationshipList"
})
@XmlRootElement(name = "l3-network")
public class L3Network
    implements AAIDatum
{

    @XmlElement(name = "network-id", required = true)
    protected String networkId;
    @XmlElement(name = "network-name", required = true)
    protected String networkName;
    @XmlElement(name = "network-type")
    protected String networkType;
    @XmlElement(name = "network-role")
    protected String networkRole;
    @XmlElement(name = "network-technology")
    protected String networkTechnology;
    @XmlElement(name = "neutron-network-id")
    protected String neutronNetworkId;
    @XmlElement(name = "is-bound-to-vpn")
    protected boolean isBoundToVpn;
    @XmlElement(name = "service-id")
    protected String serviceId;
    @XmlElement(name = "network-role-instance")
    @XmlSchemaType(name = "unsignedInt")
    protected Long networkRoleInstance;
    @XmlElement(name = "resource-version")
    protected String resourceVersion;
    @XmlElement(name = "orchestration-status")
    protected String orchestrationStatus;
    @XmlElement(name = "heat-stack-id")
    protected String heatStackId;
    @XmlElement(name = "mso-catalog-key")
    protected String msoCatalogKey;
    @XmlElement(name = "contrail-network-fqdn")
    protected String contrailNetworkFqdn;
    @XmlElement(name = "persona-model-id")
    protected String personaModelId;
    @XmlElement(name = "persona-model-version")
    protected String personaModelVersion;
    @XmlElement(name = "widget-model-id")
    protected String widgetModelId;
    @XmlElement(name = "widget-model-version")
    protected String widgetModelVersion;
    @XmlElement(name = "physical-network-name")
    protected String physicalNetworkName;
    @XmlElement(name = "is-provider-network")
    protected boolean isProviderNetwork;
    @XmlElement(name = "is-shared-network")
    protected boolean isSharedNetwork;
    @XmlElement(name = "is-external-network")
    protected boolean isExternalNetwork;
    protected Subnets subnets;
    @XmlElement(name = "ctag-assignments")
    protected CtagAssignments ctagAssignments;
    @XmlElement(name = "segmentation-assignments")
    protected SegmentationAssignments segmentationAssignments;
    @XmlElement(name = "relationship-list")
    protected RelationshipList relationshipList;

    /**
     * Gets the value of the networkId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkId() {
        return networkId;
    }

    /**
     * Sets the value of the networkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkId(String value) {
        this.networkId = value;
    }

    /**
     * Gets the value of the networkName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkName() {
        return networkName;
    }

    /**
     * Sets the value of the networkName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkName(String value) {
        this.networkName = value;
    }

    /**
     * Gets the value of the networkType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkType() {
        return networkType;
    }

    /**
     * Sets the value of the networkType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkType(String value) {
        this.networkType = value;
    }

    /**
     * Gets the value of the networkRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkRole() {
        return networkRole;
    }

    /**
     * Sets the value of the networkRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkRole(String value) {
        this.networkRole = value;
    }

    /**
     * Gets the value of the networkTechnology property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkTechnology() {
        return networkTechnology;
    }

    /**
     * Sets the value of the networkTechnology property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkTechnology(String value) {
        this.networkTechnology = value;
    }

    /**
     * Gets the value of the neutronNetworkId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeutronNetworkId() {
        return neutronNetworkId;
    }

    /**
     * Sets the value of the neutronNetworkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeutronNetworkId(String value) {
        this.neutronNetworkId = value;
    }

    /**
     * Gets the value of the isBoundToVpn property.
     * 
     */
    public boolean isIsBoundToVpn() {
        return isBoundToVpn;
    }

    /**
     * Sets the value of the isBoundToVpn property.
     * 
     */
    public void setIsBoundToVpn(boolean value) {
        this.isBoundToVpn = value;
    }

    /**
     * Gets the value of the serviceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * Sets the value of the serviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceId(String value) {
        this.serviceId = value;
    }

    /**
     * Gets the value of the networkRoleInstance property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNetworkRoleInstance() {
        return networkRoleInstance;
    }

    /**
     * Sets the value of the networkRoleInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNetworkRoleInstance(Long value) {
        this.networkRoleInstance = value;
    }

    /**
     * Gets the value of the resourceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceVersion() {
        return resourceVersion;
    }

    /**
     * Sets the value of the resourceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceVersion(String value) {
        this.resourceVersion = value;
    }

    /**
     * Gets the value of the orchestrationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrchestrationStatus() {
        return orchestrationStatus;
    }

    /**
     * Sets the value of the orchestrationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrchestrationStatus(String value) {
        this.orchestrationStatus = value;
    }

    /**
     * Gets the value of the heatStackId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeatStackId() {
        return heatStackId;
    }

    /**
     * Sets the value of the heatStackId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeatStackId(String value) {
        this.heatStackId = value;
    }

    /**
     * Gets the value of the msoCatalogKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsoCatalogKey() {
        return msoCatalogKey;
    }

    /**
     * Sets the value of the msoCatalogKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsoCatalogKey(String value) {
        this.msoCatalogKey = value;
    }

    /**
     * Gets the value of the contrailNetworkFqdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContrailNetworkFqdn() {
        return contrailNetworkFqdn;
    }

    /**
     * Sets the value of the contrailNetworkFqdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContrailNetworkFqdn(String value) {
        this.contrailNetworkFqdn = value;
    }

    /**
     * Gets the value of the personaModelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonaModelId() {
        return personaModelId;
    }

    /**
     * Sets the value of the personaModelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonaModelId(String value) {
        this.personaModelId = value;
    }

    /**
     * Gets the value of the personaModelVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonaModelVersion() {
        return personaModelVersion;
    }

    /**
     * Sets the value of the personaModelVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonaModelVersion(String value) {
        this.personaModelVersion = value;
    }

    /**
     * Gets the value of the widgetModelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidgetModelId() {
        return widgetModelId;
    }

    /**
     * Sets the value of the widgetModelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidgetModelId(String value) {
        this.widgetModelId = value;
    }

    /**
     * Gets the value of the widgetModelVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidgetModelVersion() {
        return widgetModelVersion;
    }

    /**
     * Sets the value of the widgetModelVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidgetModelVersion(String value) {
        this.widgetModelVersion = value;
    }

    /**
     * Gets the value of the physicalNetworkName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysicalNetworkName() {
        return physicalNetworkName;
    }

    /**
     * Sets the value of the physicalNetworkName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicalNetworkName(String value) {
        this.physicalNetworkName = value;
    }

    /**
     * Gets the value of the isProviderNetwork property.
     * 
     */
    public boolean isIsProviderNetwork() {
        return isProviderNetwork;
    }

    /**
     * Sets the value of the isProviderNetwork property.
     * 
     */
    public void setIsProviderNetwork(boolean value) {
        this.isProviderNetwork = value;
    }

    /**
     * Gets the value of the isSharedNetwork property.
     * 
     */
    public boolean isIsSharedNetwork() {
        return isSharedNetwork;
    }

    /**
     * Sets the value of the isSharedNetwork property.
     * 
     */
    public void setIsSharedNetwork(boolean value) {
        this.isSharedNetwork = value;
    }

    /**
     * Gets the value of the isExternalNetwork property.
     * 
     */
    public boolean isIsExternalNetwork() {
        return isExternalNetwork;
    }

    /**
     * Sets the value of the isExternalNetwork property.
     * 
     */
    public void setIsExternalNetwork(boolean value) {
        this.isExternalNetwork = value;
    }

    /**
     * Gets the value of the subnets property.
     * 
     * @return
     *     possible object is
     *     {@link Subnets }
     *     
     */
    public Subnets getSubnets() {
        return subnets;
    }

    /**
     * Sets the value of the subnets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subnets }
     *     
     */
    public void setSubnets(Subnets value) {
        this.subnets = value;
    }

    /**
     * Gets the value of the ctagAssignments property.
     * 
     * @return
     *     possible object is
     *     {@link CtagAssignments }
     *     
     */
    public CtagAssignments getCtagAssignments() {
        return ctagAssignments;
    }

    /**
     * Sets the value of the ctagAssignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtagAssignments }
     *     
     */
    public void setCtagAssignments(CtagAssignments value) {
        this.ctagAssignments = value;
    }

    /**
     * Gets the value of the segmentationAssignments property.
     * 
     * @return
     *     possible object is
     *     {@link SegmentationAssignments }
     *     
     */
    public SegmentationAssignments getSegmentationAssignments() {
        return segmentationAssignments;
    }

    /**
     * Sets the value of the segmentationAssignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link SegmentationAssignments }
     *     
     */
    public void setSegmentationAssignments(SegmentationAssignments value) {
        this.segmentationAssignments = value;
    }

    /**
     * Gets the value of the relationshipList property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipList }
     *     
     */
    public RelationshipList getRelationshipList() {
        return relationshipList;
    }

    /**
     * Sets the value of the relationshipList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipList }
     *     
     */
    public void setRelationshipList(RelationshipList value) {
        this.relationshipList = value;
    }

}
