//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 08:44:52 AM EST 
//


package org.openecomp.aai.inventory.v8;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="model-element-uuid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="new-data-del-flag" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cardinality" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="linkage-points" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="linkage-point" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="resource-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}model-elements" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}model-constraints" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}relationship-list" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modelElementUuid",
    "newDataDelFlag",
    "cardinality",
    "linkagePoints",
    "resourceVersion",
    "modelElements",
    "modelConstraints",
    "relationshipList"
})
@XmlRootElement(name = "model-element")
public class ModelElement
    implements AAIDatum
{

    @XmlElement(name = "model-element-uuid", required = true)
    protected String modelElementUuid;
    @XmlElement(name = "new-data-del-flag", required = true)
    protected String newDataDelFlag;
    @XmlElement(required = true)
    protected String cardinality;
    @XmlElement(name = "linkage-points")
    protected ModelElement.LinkagePoints linkagePoints;
    @XmlElement(name = "resource-version")
    protected String resourceVersion;
    @XmlElement(name = "model-elements")
    protected ModelElements modelElements;
    @XmlElement(name = "model-constraints")
    protected ModelConstraints modelConstraints;
    @XmlElement(name = "relationship-list")
    protected RelationshipList relationshipList;

    /**
     * Gets the value of the modelElementUuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelElementUuid() {
        return modelElementUuid;
    }

    /**
     * Sets the value of the modelElementUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelElementUuid(String value) {
        this.modelElementUuid = value;
    }

    /**
     * Gets the value of the newDataDelFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewDataDelFlag() {
        return newDataDelFlag;
    }

    /**
     * Sets the value of the newDataDelFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewDataDelFlag(String value) {
        this.newDataDelFlag = value;
    }

    /**
     * Gets the value of the cardinality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardinality() {
        return cardinality;
    }

    /**
     * Sets the value of the cardinality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardinality(String value) {
        this.cardinality = value;
    }

    /**
     * Gets the value of the linkagePoints property.
     * 
     * @return
     *     possible object is
     *     {@link ModelElement.LinkagePoints }
     *     
     */
    public ModelElement.LinkagePoints getLinkagePoints() {
        return linkagePoints;
    }

    /**
     * Sets the value of the linkagePoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelElement.LinkagePoints }
     *     
     */
    public void setLinkagePoints(ModelElement.LinkagePoints value) {
        this.linkagePoints = value;
    }

    /**
     * Gets the value of the resourceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceVersion() {
        return resourceVersion;
    }

    /**
     * Sets the value of the resourceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceVersion(String value) {
        this.resourceVersion = value;
    }

    /**
     * Gets the value of the modelElements property.
     * 
     * @return
     *     possible object is
     *     {@link ModelElements }
     *     
     */
    public ModelElements getModelElements() {
        return modelElements;
    }

    /**
     * Sets the value of the modelElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelElements }
     *     
     */
    public void setModelElements(ModelElements value) {
        this.modelElements = value;
    }

    /**
     * Gets the value of the modelConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link ModelConstraints }
     *     
     */
    public ModelConstraints getModelConstraints() {
        return modelConstraints;
    }

    /**
     * Sets the value of the modelConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelConstraints }
     *     
     */
    public void setModelConstraints(ModelConstraints value) {
        this.modelConstraints = value;
    }

    /**
     * Gets the value of the relationshipList property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipList }
     *     
     */
    public RelationshipList getRelationshipList() {
        return relationshipList;
    }

    /**
     * Sets the value of the relationshipList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipList }
     *     
     */
    public void setRelationshipList(RelationshipList value) {
        this.relationshipList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="linkage-point" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "linkagePoint"
    })
    public static class LinkagePoints
        implements AAIDatum
    {

        @XmlElement(name = "linkage-point")
        protected List<String> linkagePoint;

        /**
         * Gets the value of the linkagePoint property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the linkagePoint property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLinkagePoint().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getLinkagePoint() {
            if (linkagePoint == null) {
                linkagePoint = new ArrayList<String>();
            }
            return this.linkagePoint;
        }

    }

}
