//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.19 at 04:48:44 PM EST 
//


package org.openecomp.aai.inventory.v8;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="named-query-element-uuid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="property-collect-list" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="resource-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="property-limit-desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="do-not-output" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}named-query-elements" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}related-lookups" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}property-constraints" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}relationship-list" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "namedQueryElementUuid",
    "propertyCollectList",
    "resourceVersion",
    "propertyLimitDesc",
    "doNotOutput",
    "namedQueryElements",
    "relatedLookups",
    "propertyConstraints",
    "relationshipList"
})
@XmlRootElement(name = "named-query-element")
public class NamedQueryElement
    implements AAIDatum
{

    @XmlElement(name = "named-query-element-uuid", required = true)
    protected String namedQueryElementUuid;
    @XmlElement(name = "property-collect-list")
    protected List<String> propertyCollectList;
    @XmlElement(name = "resource-version")
    protected String resourceVersion;
    @XmlElement(name = "property-limit-desc")
    protected String propertyLimitDesc;
    @XmlElement(name = "do-not-output")
    protected String doNotOutput;
    @XmlElement(name = "named-query-elements")
    protected NamedQueryElements namedQueryElements;
    @XmlElement(name = "related-lookups")
    protected RelatedLookups relatedLookups;
    @XmlElement(name = "property-constraints")
    protected PropertyConstraints propertyConstraints;
    @XmlElement(name = "relationship-list")
    protected RelationshipList relationshipList;

    /**
     * Gets the value of the namedQueryElementUuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamedQueryElementUuid() {
        return namedQueryElementUuid;
    }

    /**
     * Sets the value of the namedQueryElementUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamedQueryElementUuid(String value) {
        this.namedQueryElementUuid = value;
    }

    /**
     * Gets the value of the propertyCollectList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertyCollectList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyCollectList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPropertyCollectList() {
        if (propertyCollectList == null) {
            propertyCollectList = new ArrayList<String>();
        }
        return this.propertyCollectList;
    }

    /**
     * Gets the value of the resourceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceVersion() {
        return resourceVersion;
    }

    /**
     * Sets the value of the resourceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceVersion(String value) {
        this.resourceVersion = value;
    }

    /**
     * Gets the value of the propertyLimitDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyLimitDesc() {
        return propertyLimitDesc;
    }

    /**
     * Sets the value of the propertyLimitDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyLimitDesc(String value) {
        this.propertyLimitDesc = value;
    }

    /**
     * Gets the value of the doNotOutput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoNotOutput() {
        return doNotOutput;
    }

    /**
     * Sets the value of the doNotOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoNotOutput(String value) {
        this.doNotOutput = value;
    }

    /**
     * Gets the value of the namedQueryElements property.
     * 
     * @return
     *     possible object is
     *     {@link NamedQueryElements }
     *     
     */
    public NamedQueryElements getNamedQueryElements() {
        return namedQueryElements;
    }

    /**
     * Sets the value of the namedQueryElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamedQueryElements }
     *     
     */
    public void setNamedQueryElements(NamedQueryElements value) {
        this.namedQueryElements = value;
    }

    /**
     * Gets the value of the relatedLookups property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedLookups }
     *     
     */
    public RelatedLookups getRelatedLookups() {
        return relatedLookups;
    }

    /**
     * Sets the value of the relatedLookups property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedLookups }
     *     
     */
    public void setRelatedLookups(RelatedLookups value) {
        this.relatedLookups = value;
    }

    /**
     * Gets the value of the propertyConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyConstraints }
     *     
     */
    public PropertyConstraints getPropertyConstraints() {
        return propertyConstraints;
    }

    /**
     * Sets the value of the propertyConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyConstraints }
     *     
     */
    public void setPropertyConstraints(PropertyConstraints value) {
        this.propertyConstraints = value;
    }

    /**
     * Gets the value of the relationshipList property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipList }
     *     
     */
    public RelationshipList getRelationshipList() {
        return relationshipList;
    }

    /**
     * Sets the value of the relationshipList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipList }
     *     
     */
    public void setRelationshipList(RelationshipList value) {
        this.relationshipList = value;
    }

}
