//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 07:59:51 PM EST 
//


package org.openecomp.aai.inventory.v8;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}logical-links" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}vnfcs" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}l3-networks" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}generic-vnfs" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}pnfs" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}physical-links" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "logicalLinks",
    "vnfcs",
    "l3Networks",
    "genericVnfs",
    "pnfs",
    "physicalLinks"
})
@XmlRootElement(name = "network")
public class Network
    implements AAIDatum
{

    @XmlElement(name = "logical-links")
    protected LogicalLinks logicalLinks;
    protected Vnfcs vnfcs;
    @XmlElement(name = "l3-networks")
    protected L3Networks l3Networks;
    @XmlElement(name = "generic-vnfs")
    protected GenericVnfs genericVnfs;
    protected Pnfs pnfs;
    @XmlElement(name = "physical-links")
    protected PhysicalLinks physicalLinks;

    /**
     * Gets the value of the logicalLinks property.
     * 
     * @return
     *     possible object is
     *     {@link LogicalLinks }
     *     
     */
    public LogicalLinks getLogicalLinks() {
        return logicalLinks;
    }

    /**
     * Sets the value of the logicalLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicalLinks }
     *     
     */
    public void setLogicalLinks(LogicalLinks value) {
        this.logicalLinks = value;
    }

    /**
     * Gets the value of the vnfcs property.
     * 
     * @return
     *     possible object is
     *     {@link Vnfcs }
     *     
     */
    public Vnfcs getVnfcs() {
        return vnfcs;
    }

    /**
     * Sets the value of the vnfcs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vnfcs }
     *     
     */
    public void setVnfcs(Vnfcs value) {
        this.vnfcs = value;
    }

    /**
     * Gets the value of the l3Networks property.
     * 
     * @return
     *     possible object is
     *     {@link L3Networks }
     *     
     */
    public L3Networks getL3Networks() {
        return l3Networks;
    }

    /**
     * Sets the value of the l3Networks property.
     * 
     * @param value
     *     allowed object is
     *     {@link L3Networks }
     *     
     */
    public void setL3Networks(L3Networks value) {
        this.l3Networks = value;
    }

    /**
     * Gets the value of the genericVnfs property.
     * 
     * @return
     *     possible object is
     *     {@link GenericVnfs }
     *     
     */
    public GenericVnfs getGenericVnfs() {
        return genericVnfs;
    }

    /**
     * Sets the value of the genericVnfs property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericVnfs }
     *     
     */
    public void setGenericVnfs(GenericVnfs value) {
        this.genericVnfs = value;
    }

    /**
     * Gets the value of the pnfs property.
     * 
     * @return
     *     possible object is
     *     {@link Pnfs }
     *     
     */
    public Pnfs getPnfs() {
        return pnfs;
    }

    /**
     * Sets the value of the pnfs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pnfs }
     *     
     */
    public void setPnfs(Pnfs value) {
        this.pnfs = value;
    }

    /**
     * Gets the value of the physicalLinks property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalLinks }
     *     
     */
    public PhysicalLinks getPhysicalLinks() {
        return physicalLinks;
    }

    /**
     * Sets the value of the physicalLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalLinks }
     *     
     */
    public void setPhysicalLinks(PhysicalLinks value) {
        this.physicalLinks = value;
    }

}
