//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 07:59:51 PM EST 
//


package org.openecomp.aai.inventory.v8;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openecomp.aai.inventory.v8 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openecomp.aai.inventory.v8
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ModelElement }
     * 
     */
    public ModelElement createModelElement() {
        return new ModelElement();
    }

    /**
     * Create an instance of {@link NamedQuery }
     * 
     */
    public NamedQuery createNamedQuery() {
        return new NamedQuery();
    }

    /**
     * Create an instance of {@link ResultData }
     * 
     */
    public ResultData createResultData() {
        return new ResultData();
    }

    /**
     * Create an instance of {@link SearchResults }
     * 
     */
    public SearchResults createSearchResults() {
        return new SearchResults();
    }

    /**
     * Create an instance of {@link Search }
     * 
     */
    public Search createSearch() {
        return new Search();
    }

    /**
     * Create an instance of {@link UpdateNodeKey }
     * 
     */
    public UpdateNodeKey createUpdateNodeKey() {
        return new UpdateNodeKey();
    }

    /**
     * Create an instance of {@link ActionData }
     * 
     */
    public ActionData createActionData() {
        return new ActionData();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link Update }
     * 
     */
    public Update createUpdate() {
        return new Update();
    }

    /**
     * Create an instance of {@link KeyData }
     * 
     */
    public KeyData createKeyData() {
        return new KeyData();
    }

    /**
     * Create an instance of {@link Notify }
     * 
     */
    public Notify createNotify() {
        return new Notify();
    }

    /**
     * Create an instance of {@link Actions }
     * 
     */
    public Actions createActions() {
        return new Actions();
    }

    /**
     * Create an instance of {@link RelationshipData }
     * 
     */
    public RelationshipData createRelationshipData() {
        return new RelationshipData();
    }

    /**
     * Create an instance of {@link RelatedToProperty }
     * 
     */
    public RelatedToProperty createRelatedToProperty() {
        return new RelatedToProperty();
    }

    /**
     * Create an instance of {@link Relationship }
     * 
     */
    public Relationship createRelationship() {
        return new Relationship();
    }

    /**
     * Create an instance of {@link RelationshipList }
     * 
     */
    public RelationshipList createRelationshipList() {
        return new RelationshipList();
    }

    /**
     * Create an instance of {@link VolumeGroup }
     * 
     */
    public VolumeGroup createVolumeGroup() {
        return new VolumeGroup();
    }

    /**
     * Create an instance of {@link VolumeGroups }
     * 
     */
    public VolumeGroups createVolumeGroups() {
        return new VolumeGroups();
    }

    /**
     * Create an instance of {@link Volume }
     * 
     */
    public Volume createVolume() {
        return new Volume();
    }

    /**
     * Create an instance of {@link Volumes }
     * 
     */
    public Volumes createVolumes() {
        return new Volumes();
    }

    /**
     * Create an instance of {@link L3InterfaceIpv4AddressList }
     * 
     */
    public L3InterfaceIpv4AddressList createL3InterfaceIpv4AddressList() {
        return new L3InterfaceIpv4AddressList();
    }

    /**
     * Create an instance of {@link L3InterfaceIpv6AddressList }
     * 
     */
    public L3InterfaceIpv6AddressList createL3InterfaceIpv6AddressList() {
        return new L3InterfaceIpv6AddressList();
    }

    /**
     * Create an instance of {@link Vlan }
     * 
     */
    public Vlan createVlan() {
        return new Vlan();
    }

    /**
     * Create an instance of {@link Vlans }
     * 
     */
    public Vlans createVlans() {
        return new Vlans();
    }

    /**
     * Create an instance of {@link LInterface }
     * 
     */
    public LInterface createLInterface() {
        return new LInterface();
    }

    /**
     * Create an instance of {@link LInterfaces }
     * 
     */
    public LInterfaces createLInterfaces() {
        return new LInterfaces();
    }

    /**
     * Create an instance of {@link Vserver }
     * 
     */
    public Vserver createVserver() {
        return new Vserver();
    }

    /**
     * Create an instance of {@link Vservers }
     * 
     */
    public Vservers createVservers() {
        return new Vservers();
    }

    /**
     * Create an instance of {@link Tenant }
     * 
     */
    public Tenant createTenant() {
        return new Tenant();
    }

    /**
     * Create an instance of {@link Tenants }
     * 
     */
    public Tenants createTenants() {
        return new Tenants();
    }

    /**
     * Create an instance of {@link Flavor }
     * 
     */
    public Flavor createFlavor() {
        return new Flavor();
    }

    /**
     * Create an instance of {@link Flavors }
     * 
     */
    public Flavors createFlavors() {
        return new Flavors();
    }

    /**
     * Create an instance of {@link GroupAssignment }
     * 
     */
    public GroupAssignment createGroupAssignment() {
        return new GroupAssignment();
    }

    /**
     * Create an instance of {@link GroupAssignments }
     * 
     */
    public GroupAssignments createGroupAssignments() {
        return new GroupAssignments();
    }

    /**
     * Create an instance of {@link Snapshot }
     * 
     */
    public Snapshot createSnapshot() {
        return new Snapshot();
    }

    /**
     * Create an instance of {@link Snapshots }
     * 
     */
    public Snapshots createSnapshots() {
        return new Snapshots();
    }

    /**
     * Create an instance of {@link Metadatum }
     * 
     */
    public Metadatum createMetadatum() {
        return new Metadatum();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Images }
     * 
     */
    public Images createImages() {
        return new Images();
    }

    /**
     * Create an instance of {@link AvailabilityZone }
     * 
     */
    public AvailabilityZone createAvailabilityZone() {
        return new AvailabilityZone();
    }

    /**
     * Create an instance of {@link AvailabilityZones }
     * 
     */
    public AvailabilityZones createAvailabilityZones() {
        return new AvailabilityZones();
    }

    /**
     * Create an instance of {@link CloudRegion }
     * 
     */
    public CloudRegion createCloudRegion() {
        return new CloudRegion();
    }

    /**
     * Create an instance of {@link CloudRegions }
     * 
     */
    public CloudRegions createCloudRegions() {
        return new CloudRegions();
    }

    /**
     * Create an instance of {@link PInterface }
     * 
     */
    public PInterface createPInterface() {
        return new PInterface();
    }

    /**
     * Create an instance of {@link PInterfaces }
     * 
     */
    public PInterfaces createPInterfaces() {
        return new PInterfaces();
    }

    /**
     * Create an instance of {@link LagInterface }
     * 
     */
    public LagInterface createLagInterface() {
        return new LagInterface();
    }

    /**
     * Create an instance of {@link LagInterfaces }
     * 
     */
    public LagInterfaces createLagInterfaces() {
        return new LagInterfaces();
    }

    /**
     * Create an instance of {@link Pserver }
     * 
     */
    public Pserver createPserver() {
        return new Pserver();
    }

    /**
     * Create an instance of {@link Pservers }
     * 
     */
    public Pservers createPservers() {
        return new Pservers();
    }

    /**
     * Create an instance of {@link CloudInfrastructure }
     * 
     */
    public CloudInfrastructure createCloudInfrastructure() {
        return new CloudInfrastructure();
    }

    /**
     * Create an instance of {@link ServiceInstance }
     * 
     */
    public ServiceInstance createServiceInstance() {
        return new ServiceInstance();
    }

    /**
     * Create an instance of {@link ServiceInstances }
     * 
     */
    public ServiceInstances createServiceInstances() {
        return new ServiceInstances();
    }

    /**
     * Create an instance of {@link ServiceSubscription }
     * 
     */
    public ServiceSubscription createServiceSubscription() {
        return new ServiceSubscription();
    }

    /**
     * Create an instance of {@link ServiceSubscriptions }
     * 
     */
    public ServiceSubscriptions createServiceSubscriptions() {
        return new ServiceSubscriptions();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link Customers }
     * 
     */
    public Customers createCustomers() {
        return new Customers();
    }

    /**
     * Create an instance of {@link Business }
     * 
     */
    public Business createBusiness() {
        return new Business();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Services }
     * 
     */
    public Services createServices() {
        return new Services();
    }

    /**
     * Create an instance of {@link ElementChoiceSet }
     * 
     */
    public ElementChoiceSet createElementChoiceSet() {
        return new ElementChoiceSet();
    }

    /**
     * Create an instance of {@link ModelElements }
     * 
     */
    public ModelElements createModelElements() {
        return new ModelElements();
    }

    /**
     * Create an instance of {@link ModelElement.LinkagePoints }
     * 
     */
    public ModelElement.LinkagePoints createModelElementLinkagePoints() {
        return new ModelElement.LinkagePoints();
    }

    /**
     * Create an instance of {@link ModelConstraints }
     * 
     */
    public ModelConstraints createModelConstraints() {
        return new ModelConstraints();
    }

    /**
     * Create an instance of {@link ModelConstraint }
     * 
     */
    public ModelConstraint createModelConstraint() {
        return new ModelConstraint();
    }

    /**
     * Create an instance of {@link ConstrainedElementSets }
     * 
     */
    public ConstrainedElementSets createConstrainedElementSets() {
        return new ConstrainedElementSets();
    }

    /**
     * Create an instance of {@link ConstrainedElementSet }
     * 
     */
    public ConstrainedElementSet createConstrainedElementSet() {
        return new ConstrainedElementSet();
    }

    /**
     * Create an instance of {@link ElementChoiceSets }
     * 
     */
    public ElementChoiceSets createElementChoiceSets() {
        return new ElementChoiceSets();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link Models }
     * 
     */
    public Models createModels() {
        return new Models();
    }

    /**
     * Create an instance of {@link RelatedLookup }
     * 
     */
    public RelatedLookup createRelatedLookup() {
        return new RelatedLookup();
    }

    /**
     * Create an instance of {@link RelatedLookups }
     * 
     */
    public RelatedLookups createRelatedLookups() {
        return new RelatedLookups();
    }

    /**
     * Create an instance of {@link PropertyConstraint }
     * 
     */
    public PropertyConstraint createPropertyConstraint() {
        return new PropertyConstraint();
    }

    /**
     * Create an instance of {@link PropertyConstraints }
     * 
     */
    public PropertyConstraints createPropertyConstraints() {
        return new PropertyConstraints();
    }

    /**
     * Create an instance of {@link NamedQueryElement }
     * 
     */
    public NamedQueryElement createNamedQueryElement() {
        return new NamedQueryElement();
    }

    /**
     * Create an instance of {@link NamedQueryElements }
     * 
     */
    public NamedQueryElements createNamedQueryElements() {
        return new NamedQueryElements();
    }

    /**
     * Create an instance of {@link NamedQuery.RequiredInputParams }
     * 
     */
    public NamedQuery.RequiredInputParams createNamedQueryRequiredInputParams() {
        return new NamedQuery.RequiredInputParams();
    }

    /**
     * Create an instance of {@link NamedQueries }
     * 
     */
    public NamedQueries createNamedQueries() {
        return new NamedQueries();
    }

    /**
     * Create an instance of {@link ServiceDesignAndCreation }
     * 
     */
    public ServiceDesignAndCreation createServiceDesignAndCreation() {
        return new ServiceDesignAndCreation();
    }

    /**
     * Create an instance of {@link LogicalLink }
     * 
     */
    public LogicalLink createLogicalLink() {
        return new LogicalLink();
    }

    /**
     * Create an instance of {@link LogicalLinks }
     * 
     */
    public LogicalLinks createLogicalLinks() {
        return new LogicalLinks();
    }

    /**
     * Create an instance of {@link Vnfc }
     * 
     */
    public Vnfc createVnfc() {
        return new Vnfc();
    }

    /**
     * Create an instance of {@link Vnfcs }
     * 
     */
    public Vnfcs createVnfcs() {
        return new Vnfcs();
    }

    /**
     * Create an instance of {@link Subnet }
     * 
     */
    public Subnet createSubnet() {
        return new Subnet();
    }

    /**
     * Create an instance of {@link Subnets }
     * 
     */
    public Subnets createSubnets() {
        return new Subnets();
    }

    /**
     * Create an instance of {@link CtagAssignment }
     * 
     */
    public CtagAssignment createCtagAssignment() {
        return new CtagAssignment();
    }

    /**
     * Create an instance of {@link CtagAssignments }
     * 
     */
    public CtagAssignments createCtagAssignments() {
        return new CtagAssignments();
    }

    /**
     * Create an instance of {@link SegmentationAssignment }
     * 
     */
    public SegmentationAssignment createSegmentationAssignment() {
        return new SegmentationAssignment();
    }

    /**
     * Create an instance of {@link SegmentationAssignments }
     * 
     */
    public SegmentationAssignments createSegmentationAssignments() {
        return new SegmentationAssignments();
    }

    /**
     * Create an instance of {@link L3Network }
     * 
     */
    public L3Network createL3Network() {
        return new L3Network();
    }

    /**
     * Create an instance of {@link L3Networks }
     * 
     */
    public L3Networks createL3Networks() {
        return new L3Networks();
    }

    /**
     * Create an instance of {@link VfModule }
     * 
     */
    public VfModule createVfModule() {
        return new VfModule();
    }

    /**
     * Create an instance of {@link VfModules }
     * 
     */
    public VfModules createVfModules() {
        return new VfModules();
    }

    /**
     * Create an instance of {@link GenericVnf }
     * 
     */
    public GenericVnf createGenericVnf() {
        return new GenericVnf();
    }

    /**
     * Create an instance of {@link GenericVnfs }
     * 
     */
    public GenericVnfs createGenericVnfs() {
        return new GenericVnfs();
    }

    /**
     * Create an instance of {@link Pnf }
     * 
     */
    public Pnf createPnf() {
        return new Pnf();
    }

    /**
     * Create an instance of {@link Pnfs }
     * 
     */
    public Pnfs createPnfs() {
        return new Pnfs();
    }

    /**
     * Create an instance of {@link PhysicalLink }
     * 
     */
    public PhysicalLink createPhysicalLink() {
        return new PhysicalLink();
    }

    /**
     * Create an instance of {@link PhysicalLinks }
     * 
     */
    public PhysicalLinks createPhysicalLinks() {
        return new PhysicalLinks();
    }

    /**
     * Create an instance of {@link Network }
     * 
     */
    public Network createNetwork() {
        return new Network();
    }

    /**
     * Create an instance of {@link ReservedPropNames }
     * 
     */
    public ReservedPropNames createReservedPropNames() {
        return new ReservedPropNames();
    }

    /**
     * Create an instance of {@link EdgePropNames }
     * 
     */
    public EdgePropNames createEdgePropNames() {
        return new EdgePropNames();
    }

    /**
     * Create an instance of {@link AaiInternal }
     * 
     */
    public AaiInternal createAaiInternal() {
        return new AaiInternal();
    }

    /**
     * Create an instance of {@link Inventory }
     * 
     */
    public Inventory createInventory() {
        return new Inventory();
    }

    /**
     * Create an instance of {@link InventoryItemData }
     * 
     */
    public InventoryItemData createInventoryItemData() {
        return new InventoryItemData();
    }

    /**
     * Create an instance of {@link InventoryItem }
     * 
     */
    public InventoryItem createInventoryItem() {
        return new InventoryItem();
    }

    /**
     * Create an instance of {@link TaggedInventoryItemList }
     * 
     */
    public TaggedInventoryItemList createTaggedInventoryItemList() {
        return new TaggedInventoryItemList();
    }

    /**
     * Create an instance of {@link StartNodeFilter }
     * 
     */
    public StartNodeFilter createStartNodeFilter() {
        return new StartNodeFilter();
    }

    /**
     * Create an instance of {@link IncludeNodeFilter }
     * 
     */
    public IncludeNodeFilter createIncludeNodeFilter() {
        return new IncludeNodeFilter();
    }

    /**
     * Create an instance of {@link SecondaryFilter }
     * 
     */
    public SecondaryFilter createSecondaryFilter() {
        return new SecondaryFilter();
    }

    /**
     * Create an instance of {@link NotificationEventHeader }
     * 
     */
    public NotificationEventHeader createNotificationEventHeader() {
        return new NotificationEventHeader();
    }

    /**
     * Create an instance of {@link NotificationEvent }
     * 
     */
    public NotificationEvent createNotificationEvent() {
        return new NotificationEvent();
    }

    /**
     * Create an instance of {@link QueryParameters }
     * 
     */
    public QueryParameters createQueryParameters() {
        return new QueryParameters();
    }

    /**
     * Create an instance of {@link InstanceFilter }
     * 
     */
    public InstanceFilter createInstanceFilter() {
        return new InstanceFilter();
    }

    /**
     * Create an instance of {@link InstanceFilters }
     * 
     */
    public InstanceFilters createInstanceFilters() {
        return new InstanceFilters();
    }

    /**
     * Create an instance of {@link ModelAndNamedQuerySearch }
     * 
     */
    public ModelAndNamedQuerySearch createModelAndNamedQuerySearch() {
        return new ModelAndNamedQuerySearch();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link ExtraProperties }
     * 
     */
    public ExtraProperties createExtraProperties() {
        return new ExtraProperties();
    }

    /**
     * Create an instance of {@link InventoryResponseItem }
     * 
     */
    public InventoryResponseItem createInventoryResponseItem() {
        return new InventoryResponseItem();
    }

    /**
     * Create an instance of {@link InventoryResponseItems }
     * 
     */
    public InventoryResponseItems createInventoryResponseItems() {
        return new InventoryResponseItems();
    }

    /**
     * Create an instance of {@link ResponseList }
     * 
     */
    public ResponseList createResponseList() {
        return new ResponseList();
    }

    /**
     * Create an instance of {@link ExtraProperty }
     * 
     */
    public ExtraProperty createExtraProperty() {
        return new ExtraProperty();
    }

}
