//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.19 at 04:48:44 PM EST 
//


package org.openecomp.aai.inventory.v8;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pnf-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="pnf-name2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pnf-name2-source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pnf-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="equip-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="equip-vendor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="equip-model" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="management-option" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ipaddress-v4-oam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sw-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="orchestration-status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="in-maint" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="frame-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resource-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}relationship-list" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}p-interfaces" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}lag-interfaces" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pnfName",
    "pnfName2",
    "pnfName2Source",
    "pnfId",
    "equipType",
    "equipVendor",
    "equipModel",
    "managementOption",
    "ipaddressV4Oam",
    "swVersion",
    "orchestrationStatus",
    "inMaint",
    "frameId",
    "resourceVersion",
    "relationshipList",
    "pInterfaces",
    "lagInterfaces"
})
@XmlRootElement(name = "pnf")
public class Pnf
    implements AAIDatum
{

    @XmlElement(name = "pnf-name", required = true)
    protected String pnfName;
    @XmlElement(name = "pnf-name2")
    protected String pnfName2;
    @XmlElement(name = "pnf-name2-source")
    protected String pnfName2Source;
    @XmlElement(name = "pnf-id")
    protected String pnfId;
    @XmlElement(name = "equip-type")
    protected String equipType;
    @XmlElement(name = "equip-vendor")
    protected String equipVendor;
    @XmlElement(name = "equip-model")
    protected String equipModel;
    @XmlElement(name = "management-option")
    protected String managementOption;
    @XmlElement(name = "ipaddress-v4-oam")
    protected String ipaddressV4Oam;
    @XmlElement(name = "sw-version")
    protected String swVersion;
    @XmlElement(name = "orchestration-status")
    protected String orchestrationStatus;
    @XmlElement(name = "in-maint")
    protected boolean inMaint;
    @XmlElement(name = "frame-id")
    protected String frameId;
    @XmlElement(name = "resource-version")
    protected String resourceVersion;
    @XmlElement(name = "relationship-list")
    protected RelationshipList relationshipList;
    @XmlElement(name = "p-interfaces")
    protected PInterfaces pInterfaces;
    @XmlElement(name = "lag-interfaces")
    protected LagInterfaces lagInterfaces;

    /**
     * Gets the value of the pnfName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPnfName() {
        return pnfName;
    }

    /**
     * Sets the value of the pnfName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPnfName(String value) {
        this.pnfName = value;
    }

    /**
     * Gets the value of the pnfName2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPnfName2() {
        return pnfName2;
    }

    /**
     * Sets the value of the pnfName2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPnfName2(String value) {
        this.pnfName2 = value;
    }

    /**
     * Gets the value of the pnfName2Source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPnfName2Source() {
        return pnfName2Source;
    }

    /**
     * Sets the value of the pnfName2Source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPnfName2Source(String value) {
        this.pnfName2Source = value;
    }

    /**
     * Gets the value of the pnfId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPnfId() {
        return pnfId;
    }

    /**
     * Sets the value of the pnfId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPnfId(String value) {
        this.pnfId = value;
    }

    /**
     * Gets the value of the equipType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipType() {
        return equipType;
    }

    /**
     * Sets the value of the equipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipType(String value) {
        this.equipType = value;
    }

    /**
     * Gets the value of the equipVendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipVendor() {
        return equipVendor;
    }

    /**
     * Sets the value of the equipVendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipVendor(String value) {
        this.equipVendor = value;
    }

    /**
     * Gets the value of the equipModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipModel() {
        return equipModel;
    }

    /**
     * Sets the value of the equipModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipModel(String value) {
        this.equipModel = value;
    }

    /**
     * Gets the value of the managementOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagementOption() {
        return managementOption;
    }

    /**
     * Sets the value of the managementOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagementOption(String value) {
        this.managementOption = value;
    }

    /**
     * Gets the value of the ipaddressV4Oam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpaddressV4Oam() {
        return ipaddressV4Oam;
    }

    /**
     * Sets the value of the ipaddressV4Oam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpaddressV4Oam(String value) {
        this.ipaddressV4Oam = value;
    }

    /**
     * Gets the value of the swVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwVersion() {
        return swVersion;
    }

    /**
     * Sets the value of the swVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwVersion(String value) {
        this.swVersion = value;
    }

    /**
     * Gets the value of the orchestrationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrchestrationStatus() {
        return orchestrationStatus;
    }

    /**
     * Sets the value of the orchestrationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrchestrationStatus(String value) {
        this.orchestrationStatus = value;
    }

    /**
     * Gets the value of the inMaint property.
     * 
     */
    public boolean isInMaint() {
        return inMaint;
    }

    /**
     * Sets the value of the inMaint property.
     * 
     */
    public void setInMaint(boolean value) {
        this.inMaint = value;
    }

    /**
     * Gets the value of the frameId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameId() {
        return frameId;
    }

    /**
     * Sets the value of the frameId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameId(String value) {
        this.frameId = value;
    }

    /**
     * Gets the value of the resourceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceVersion() {
        return resourceVersion;
    }

    /**
     * Sets the value of the resourceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceVersion(String value) {
        this.resourceVersion = value;
    }

    /**
     * Gets the value of the relationshipList property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipList }
     *     
     */
    public RelationshipList getRelationshipList() {
        return relationshipList;
    }

    /**
     * Sets the value of the relationshipList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipList }
     *     
     */
    public void setRelationshipList(RelationshipList value) {
        this.relationshipList = value;
    }

    /**
     * Gets the value of the pInterfaces property.
     * 
     * @return
     *     possible object is
     *     {@link PInterfaces }
     *     
     */
    public PInterfaces getPInterfaces() {
        return pInterfaces;
    }

    /**
     * Sets the value of the pInterfaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link PInterfaces }
     *     
     */
    public void setPInterfaces(PInterfaces value) {
        this.pInterfaces = value;
    }

    /**
     * Gets the value of the lagInterfaces property.
     * 
     * @return
     *     possible object is
     *     {@link LagInterfaces }
     *     
     */
    public LagInterfaces getLagInterfaces() {
        return lagInterfaces;
    }

    /**
     * Sets the value of the lagInterfaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link LagInterfaces }
     *     
     */
    public void setLagInterfaces(LagInterfaces value) {
        this.lagInterfaces = value;
    }

}
