//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.14 at 01:05:25 PM EST 
//


package org.openecomp.aai.inventory.v8;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="related-lookup-uuid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="source-node-type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="source-node-property" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="target-node-type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="target-node-property" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="property-collect-list" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="resource-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}relationship-list" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "relatedLookupUuid",
    "sourceNodeType",
    "sourceNodeProperty",
    "targetNodeType",
    "targetNodeProperty",
    "propertyCollectList",
    "resourceVersion",
    "relationshipList"
})
@XmlRootElement(name = "related-lookup")
public class RelatedLookup
    implements AAIDatum
{

    @XmlElement(name = "related-lookup-uuid", required = true)
    protected String relatedLookupUuid;
    @XmlElement(name = "source-node-type", required = true)
    protected String sourceNodeType;
    @XmlElement(name = "source-node-property", required = true)
    protected String sourceNodeProperty;
    @XmlElement(name = "target-node-type", required = true)
    protected String targetNodeType;
    @XmlElement(name = "target-node-property", required = true)
    protected String targetNodeProperty;
    @XmlElement(name = "property-collect-list")
    protected List<String> propertyCollectList;
    @XmlElement(name = "resource-version")
    protected String resourceVersion;
    @XmlElement(name = "relationship-list")
    protected RelationshipList relationshipList;

    /**
     * Gets the value of the relatedLookupUuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedLookupUuid() {
        return relatedLookupUuid;
    }

    /**
     * Sets the value of the relatedLookupUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedLookupUuid(String value) {
        this.relatedLookupUuid = value;
    }

    /**
     * Gets the value of the sourceNodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceNodeType() {
        return sourceNodeType;
    }

    /**
     * Sets the value of the sourceNodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceNodeType(String value) {
        this.sourceNodeType = value;
    }

    /**
     * Gets the value of the sourceNodeProperty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceNodeProperty() {
        return sourceNodeProperty;
    }

    /**
     * Sets the value of the sourceNodeProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceNodeProperty(String value) {
        this.sourceNodeProperty = value;
    }

    /**
     * Gets the value of the targetNodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetNodeType() {
        return targetNodeType;
    }

    /**
     * Sets the value of the targetNodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetNodeType(String value) {
        this.targetNodeType = value;
    }

    /**
     * Gets the value of the targetNodeProperty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetNodeProperty() {
        return targetNodeProperty;
    }

    /**
     * Sets the value of the targetNodeProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetNodeProperty(String value) {
        this.targetNodeProperty = value;
    }

    /**
     * Gets the value of the propertyCollectList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertyCollectList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyCollectList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPropertyCollectList() {
        if (propertyCollectList == null) {
            propertyCollectList = new ArrayList<String>();
        }
        return this.propertyCollectList;
    }

    /**
     * Gets the value of the resourceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceVersion() {
        return resourceVersion;
    }

    /**
     * Sets the value of the resourceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceVersion(String value) {
        this.resourceVersion = value;
    }

    /**
     * Gets the value of the relationshipList property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipList }
     *     
     */
    public RelationshipList getRelationshipList() {
        return relationshipList;
    }

    /**
     * Sets the value of the relationshipList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipList }
     *     
     */
    public void setRelationshipList(RelationshipList value) {
        this.relationshipList = value;
    }

}
