//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 08:44:52 AM EST 
//


package org.openecomp.aai.inventory.v8;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="service-instance-id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="service-instance-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="persona-model-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="persona-model-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="widget-model-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="widget-model-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bandwidth-total" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bandwidth-up-wan1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bandwidth-down-wan1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bandwidth-up-wan2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bandwidth-down-wan2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vhn-portal-url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="operational-status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="service-instance-location-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resource-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}relationship-list" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}metadata" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serviceInstanceId",
    "serviceInstanceName",
    "personaModelId",
    "personaModelVersion",
    "widgetModelId",
    "widgetModelVersion",
    "bandwidthTotal",
    "bandwidthUpWan1",
    "bandwidthDownWan1",
    "bandwidthUpWan2",
    "bandwidthDownWan2",
    "vhnPortalUrl",
    "operationalStatus",
    "serviceInstanceLocationId",
    "resourceVersion",
    "relationshipList",
    "metadata"
})
@XmlRootElement(name = "service-instance")
public class ServiceInstance
    implements AAIDatum
{

    @XmlElement(name = "service-instance-id", required = true)
    protected String serviceInstanceId;
    @XmlElement(name = "service-instance-name")
    protected String serviceInstanceName;
    @XmlElement(name = "persona-model-id")
    protected String personaModelId;
    @XmlElement(name = "persona-model-version")
    protected String personaModelVersion;
    @XmlElement(name = "widget-model-id")
    protected String widgetModelId;
    @XmlElement(name = "widget-model-version")
    protected String widgetModelVersion;
    @XmlElement(name = "bandwidth-total")
    protected String bandwidthTotal;
    @XmlElement(name = "bandwidth-up-wan1")
    protected String bandwidthUpWan1;
    @XmlElement(name = "bandwidth-down-wan1")
    protected String bandwidthDownWan1;
    @XmlElement(name = "bandwidth-up-wan2")
    protected String bandwidthUpWan2;
    @XmlElement(name = "bandwidth-down-wan2")
    protected String bandwidthDownWan2;
    @XmlElement(name = "vhn-portal-url")
    protected String vhnPortalUrl;
    @XmlElement(name = "operational-status")
    protected String operationalStatus;
    @XmlElement(name = "service-instance-location-id")
    protected String serviceInstanceLocationId;
    @XmlElement(name = "resource-version")
    protected String resourceVersion;
    @XmlElement(name = "relationship-list")
    protected RelationshipList relationshipList;
    protected Metadata metadata;

    /**
     * Gets the value of the serviceInstanceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceInstanceId() {
        return serviceInstanceId;
    }

    /**
     * Sets the value of the serviceInstanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceInstanceId(String value) {
        this.serviceInstanceId = value;
    }

    /**
     * Gets the value of the serviceInstanceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceInstanceName() {
        return serviceInstanceName;
    }

    /**
     * Sets the value of the serviceInstanceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceInstanceName(String value) {
        this.serviceInstanceName = value;
    }

    /**
     * Gets the value of the personaModelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonaModelId() {
        return personaModelId;
    }

    /**
     * Sets the value of the personaModelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonaModelId(String value) {
        this.personaModelId = value;
    }

    /**
     * Gets the value of the personaModelVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonaModelVersion() {
        return personaModelVersion;
    }

    /**
     * Sets the value of the personaModelVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonaModelVersion(String value) {
        this.personaModelVersion = value;
    }

    /**
     * Gets the value of the widgetModelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidgetModelId() {
        return widgetModelId;
    }

    /**
     * Sets the value of the widgetModelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidgetModelId(String value) {
        this.widgetModelId = value;
    }

    /**
     * Gets the value of the widgetModelVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidgetModelVersion() {
        return widgetModelVersion;
    }

    /**
     * Sets the value of the widgetModelVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidgetModelVersion(String value) {
        this.widgetModelVersion = value;
    }

    /**
     * Gets the value of the bandwidthTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBandwidthTotal() {
        return bandwidthTotal;
    }

    /**
     * Sets the value of the bandwidthTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBandwidthTotal(String value) {
        this.bandwidthTotal = value;
    }

    /**
     * Gets the value of the bandwidthUpWan1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBandwidthUpWan1() {
        return bandwidthUpWan1;
    }

    /**
     * Sets the value of the bandwidthUpWan1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBandwidthUpWan1(String value) {
        this.bandwidthUpWan1 = value;
    }

    /**
     * Gets the value of the bandwidthDownWan1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBandwidthDownWan1() {
        return bandwidthDownWan1;
    }

    /**
     * Sets the value of the bandwidthDownWan1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBandwidthDownWan1(String value) {
        this.bandwidthDownWan1 = value;
    }

    /**
     * Gets the value of the bandwidthUpWan2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBandwidthUpWan2() {
        return bandwidthUpWan2;
    }

    /**
     * Sets the value of the bandwidthUpWan2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBandwidthUpWan2(String value) {
        this.bandwidthUpWan2 = value;
    }

    /**
     * Gets the value of the bandwidthDownWan2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBandwidthDownWan2() {
        return bandwidthDownWan2;
    }

    /**
     * Sets the value of the bandwidthDownWan2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBandwidthDownWan2(String value) {
        this.bandwidthDownWan2 = value;
    }

    /**
     * Gets the value of the vhnPortalUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVhnPortalUrl() {
        return vhnPortalUrl;
    }

    /**
     * Sets the value of the vhnPortalUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVhnPortalUrl(String value) {
        this.vhnPortalUrl = value;
    }

    /**
     * Gets the value of the operationalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationalStatus() {
        return operationalStatus;
    }

    /**
     * Sets the value of the operationalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationalStatus(String value) {
        this.operationalStatus = value;
    }

    /**
     * Gets the value of the serviceInstanceLocationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceInstanceLocationId() {
        return serviceInstanceLocationId;
    }

    /**
     * Sets the value of the serviceInstanceLocationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceInstanceLocationId(String value) {
        this.serviceInstanceLocationId = value;
    }

    /**
     * Gets the value of the resourceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceVersion() {
        return resourceVersion;
    }

    /**
     * Sets the value of the resourceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceVersion(String value) {
        this.resourceVersion = value;
    }

    /**
     * Gets the value of the relationshipList property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipList }
     *     
     */
    public RelationshipList getRelationshipList() {
        return relationshipList;
    }

    /**
     * Sets the value of the relationshipList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipList }
     *     
     */
    public void setRelationshipList(RelationshipList value) {
        this.relationshipList = value;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link Metadata }
     *     
     */
    public Metadata getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Metadata }
     *     
     */
    public void setMetadata(Metadata value) {
        this.metadata = value;
    }

}
