//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.20 at 02:31:54 PM EST 
//


package org.openecomp.aai.inventory.v8;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="vlan-interface" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="vlan-id-inner" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="vlan-id-outer" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="resource-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="speed-value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="speed-units" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vlan-description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="backdoor-connection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vpn-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}relationship-list" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}l3-interface-ipv4-address-list" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}l3-interface-ipv6-address-list" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vlanInterface",
    "vlanIdInner",
    "vlanIdOuter",
    "resourceVersion",
    "speedValue",
    "speedUnits",
    "vlanDescription",
    "backdoorConnection",
    "vpnId",
    "relationshipList",
    "l3InterfaceIpv4AddressList",
    "l3InterfaceIpv6AddressList"
})
@XmlRootElement(name = "vlan")
public class Vlan
    implements AAIDatum
{

    @XmlElement(name = "vlan-interface", required = true)
    protected String vlanInterface;
    @XmlElement(name = "vlan-id-inner")
    @XmlSchemaType(name = "unsignedInt")
    protected Long vlanIdInner;
    @XmlElement(name = "vlan-id-outer")
    @XmlSchemaType(name = "unsignedInt")
    protected Long vlanIdOuter;
    @XmlElement(name = "resource-version")
    protected String resourceVersion;
    @XmlElement(name = "speed-value")
    protected String speedValue;
    @XmlElement(name = "speed-units")
    protected String speedUnits;
    @XmlElement(name = "vlan-description")
    protected String vlanDescription;
    @XmlElement(name = "backdoor-connection")
    protected String backdoorConnection;
    @XmlElement(name = "vpn-id")
    protected String vpnId;
    @XmlElement(name = "relationship-list")
    protected RelationshipList relationshipList;
    @XmlElement(name = "l3-interface-ipv4-address-list")
    protected List<L3InterfaceIpv4AddressList> l3InterfaceIpv4AddressList;
    @XmlElement(name = "l3-interface-ipv6-address-list")
    protected List<L3InterfaceIpv6AddressList> l3InterfaceIpv6AddressList;

    /**
     * Gets the value of the vlanInterface property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVlanInterface() {
        return vlanInterface;
    }

    /**
     * Sets the value of the vlanInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVlanInterface(String value) {
        this.vlanInterface = value;
    }

    /**
     * Gets the value of the vlanIdInner property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVlanIdInner() {
        return vlanIdInner;
    }

    /**
     * Sets the value of the vlanIdInner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVlanIdInner(Long value) {
        this.vlanIdInner = value;
    }

    /**
     * Gets the value of the vlanIdOuter property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVlanIdOuter() {
        return vlanIdOuter;
    }

    /**
     * Sets the value of the vlanIdOuter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVlanIdOuter(Long value) {
        this.vlanIdOuter = value;
    }

    /**
     * Gets the value of the resourceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceVersion() {
        return resourceVersion;
    }

    /**
     * Sets the value of the resourceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceVersion(String value) {
        this.resourceVersion = value;
    }

    /**
     * Gets the value of the speedValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeedValue() {
        return speedValue;
    }

    /**
     * Sets the value of the speedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeedValue(String value) {
        this.speedValue = value;
    }

    /**
     * Gets the value of the speedUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeedUnits() {
        return speedUnits;
    }

    /**
     * Sets the value of the speedUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeedUnits(String value) {
        this.speedUnits = value;
    }

    /**
     * Gets the value of the vlanDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVlanDescription() {
        return vlanDescription;
    }

    /**
     * Sets the value of the vlanDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVlanDescription(String value) {
        this.vlanDescription = value;
    }

    /**
     * Gets the value of the backdoorConnection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackdoorConnection() {
        return backdoorConnection;
    }

    /**
     * Sets the value of the backdoorConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackdoorConnection(String value) {
        this.backdoorConnection = value;
    }

    /**
     * Gets the value of the vpnId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVpnId() {
        return vpnId;
    }

    /**
     * Sets the value of the vpnId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVpnId(String value) {
        this.vpnId = value;
    }

    /**
     * Gets the value of the relationshipList property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipList }
     *     
     */
    public RelationshipList getRelationshipList() {
        return relationshipList;
    }

    /**
     * Sets the value of the relationshipList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipList }
     *     
     */
    public void setRelationshipList(RelationshipList value) {
        this.relationshipList = value;
    }

    /**
     * Gets the value of the l3InterfaceIpv4AddressList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the l3InterfaceIpv4AddressList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getL3InterfaceIpv4AddressList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link L3InterfaceIpv4AddressList }
     * 
     * 
     */
    public List<L3InterfaceIpv4AddressList> getL3InterfaceIpv4AddressList() {
        if (l3InterfaceIpv4AddressList == null) {
            l3InterfaceIpv4AddressList = new ArrayList<L3InterfaceIpv4AddressList>();
        }
        return this.l3InterfaceIpv4AddressList;
    }

    /**
     * Gets the value of the l3InterfaceIpv6AddressList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the l3InterfaceIpv6AddressList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getL3InterfaceIpv6AddressList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link L3InterfaceIpv6AddressList }
     * 
     * 
     */
    public List<L3InterfaceIpv6AddressList> getL3InterfaceIpv6AddressList() {
        if (l3InterfaceIpv6AddressList == null) {
            l3InterfaceIpv6AddressList = new ArrayList<L3InterfaceIpv6AddressList>();
        }
        return this.l3InterfaceIpv6AddressList;
    }

}
