//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.19 at 04:48:44 PM EST 
//


package org.openecomp.aai.inventory.v8;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openecomp.sdnc.sli.aai.data.AAIDatum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="vserver-id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="vserver-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="vserver-name2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="prov-status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vserver-selflink" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="in-maint" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="is-closed-loop-disabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="resource-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}volumes" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}relationship-list" minOccurs="0"/&gt;
 *         &lt;element ref="{http://org.openecomp.aai.inventory/v8}l-interfaces" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vserverId",
    "vserverName",
    "vserverName2",
    "provStatus",
    "vserverSelflink",
    "inMaint",
    "isClosedLoopDisabled",
    "resourceVersion",
    "volumes",
    "relationshipList",
    "lInterfaces"
})
@XmlRootElement(name = "vserver")
public class Vserver
    implements AAIDatum
{

    @XmlElement(name = "vserver-id", required = true)
    protected String vserverId;
    @XmlElement(name = "vserver-name", required = true)
    protected String vserverName;
    @XmlElement(name = "vserver-name2")
    protected String vserverName2;
    @XmlElement(name = "prov-status")
    protected String provStatus;
    @XmlElement(name = "vserver-selflink", required = true)
    protected String vserverSelflink;
    @XmlElement(name = "in-maint")
    protected boolean inMaint;
    @XmlElement(name = "is-closed-loop-disabled")
    protected boolean isClosedLoopDisabled;
    @XmlElement(name = "resource-version")
    protected String resourceVersion;
    protected Volumes volumes;
    @XmlElement(name = "relationship-list")
    protected RelationshipList relationshipList;
    @XmlElement(name = "l-interfaces")
    protected LInterfaces lInterfaces;

    /**
     * Gets the value of the vserverId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVserverId() {
        return vserverId;
    }

    /**
     * Sets the value of the vserverId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVserverId(String value) {
        this.vserverId = value;
    }

    /**
     * Gets the value of the vserverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVserverName() {
        return vserverName;
    }

    /**
     * Sets the value of the vserverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVserverName(String value) {
        this.vserverName = value;
    }

    /**
     * Gets the value of the vserverName2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVserverName2() {
        return vserverName2;
    }

    /**
     * Sets the value of the vserverName2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVserverName2(String value) {
        this.vserverName2 = value;
    }

    /**
     * Gets the value of the provStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvStatus() {
        return provStatus;
    }

    /**
     * Sets the value of the provStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvStatus(String value) {
        this.provStatus = value;
    }

    /**
     * Gets the value of the vserverSelflink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVserverSelflink() {
        return vserverSelflink;
    }

    /**
     * Sets the value of the vserverSelflink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVserverSelflink(String value) {
        this.vserverSelflink = value;
    }

    /**
     * Gets the value of the inMaint property.
     * 
     */
    public boolean isInMaint() {
        return inMaint;
    }

    /**
     * Sets the value of the inMaint property.
     * 
     */
    public void setInMaint(boolean value) {
        this.inMaint = value;
    }

    /**
     * Gets the value of the isClosedLoopDisabled property.
     * 
     */
    public boolean isIsClosedLoopDisabled() {
        return isClosedLoopDisabled;
    }

    /**
     * Sets the value of the isClosedLoopDisabled property.
     * 
     */
    public void setIsClosedLoopDisabled(boolean value) {
        this.isClosedLoopDisabled = value;
    }

    /**
     * Gets the value of the resourceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceVersion() {
        return resourceVersion;
    }

    /**
     * Sets the value of the resourceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceVersion(String value) {
        this.resourceVersion = value;
    }

    /**
     * Gets the value of the volumes property.
     * 
     * @return
     *     possible object is
     *     {@link Volumes }
     *     
     */
    public Volumes getVolumes() {
        return volumes;
    }

    /**
     * Sets the value of the volumes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Volumes }
     *     
     */
    public void setVolumes(Volumes value) {
        this.volumes = value;
    }

    /**
     * Gets the value of the relationshipList property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipList }
     *     
     */
    public RelationshipList getRelationshipList() {
        return relationshipList;
    }

    /**
     * Sets the value of the relationshipList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipList }
     *     
     */
    public void setRelationshipList(RelationshipList value) {
        this.relationshipList = value;
    }

    /**
     * Gets the value of the lInterfaces property.
     * 
     * @return
     *     possible object is
     *     {@link LInterfaces }
     *     
     */
    public LInterfaces getLInterfaces() {
        return lInterfaces;
    }

    /**
     * Sets the value of the lInterfaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link LInterfaces }
     *     
     */
    public void setLInterfaces(LInterfaces value) {
        this.lInterfaces = value;
    }

}
